import os
import re
import json

WORKSPACE_ROOT = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev"
MC_DIR = os.path.join(WORKSPACE_ROOT, "minecraft")
REPORT_PATH = os.path.join(MC_DIR, "ai_audit_report.md")

audit_results = {
    "deliverable_present": False,
    "deliverable_size": 0,
    "deliverable_lines": 0,
    "citations_tested": [],
    "citation_failures": [],
    "kubejs_scripts_tested": [],
    "kubejs_script_discrepancies": [],
    "python_scripts_tested": [],
    "python_script_discrepancies": [],
    "quest_verification": {},
    "ore_report_verification": {},
    "empty_dirs_verification": {},
    "full_filesystem_census": {},
    "worker_artifact_verification": {}
}

# 1. Check deliverable existence
if os.path.exists(REPORT_PATH):
    audit_results["deliverable_present"] = True
    audit_results["deliverable_size"] = os.path.getsize(REPORT_PATH)
    with open(REPORT_PATH, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()
        audit_results["deliverable_lines"] = len(lines)
        report_content = "".join(lines)

# 2. Test specific primary citations from the report
PRIMARY_CITATIONS = [
    # Cat 1
    {"file": r"kubejs\server_scripts\00_tags.js", "line": 1, "pattern": "Auto-generated by Antigravity: Tag unifications"},
    {"file": r"kubejs\server_scripts\20_fixed_datapacks.js", "line": 1, "pattern": "Auto-generated by Antigravity to fix broken datapack recipes"},
    {"file": r"kubejs\server_scripts\convert_to_js.py", "line": 9, "pattern": "Auto-generated by Antigravity to fix broken datapack recipes"},
    {"file": r"kubejs\assets\minecraft\models\block\flowerbed_1.json", "line": 2, "pattern": "Made with Blockbench / Fixed by Antigravity"},
    {"file": r"kubejs\assets\minecraft\models\block\flowerbed_2.json", "line": 2, "pattern": "Made with Blockbench / Fixed by Antigravity"},
    {"file": r"kubejs\assets\minecraft\models\block\flowerbed_3.json", "line": 2, "pattern": "Made with Blockbench / Fixed by Antigravity"},
    {"file": r"kubejs\assets\minecraft\models\block\flowerbed_4.json", "line": 2, "pattern": "Made with Blockbench / Fixed by Antigravity"},
    {"file": r"check_client_toml.py", "line": 8, "pattern": "List from user prompt"},
    {"file": r"generate_high_priority_data.py", "line": 47, "pattern": "Archivo generado"},
    {"file": r"scratch\mod_extraction\convert_recipes.py", "line": 97, "pattern": "Archivo generado"},
    # Cat 2
    {"file": r"kubejs\server_scripts\expert_mode_recipes.js", "line": 65, "pattern": "handled in prompt 2"},
    {"file": r"kubejs\server_scripts\03_pneumatic_mekanism_gates.js", "line": 298, "pattern": "further refined in Prompt 4"},
    {"file": r"kubejs\server_scripts\03_pneumatic_mekanism_gates.js", "line": 311, "pattern": "fully defined in Prompt 4"},
    {"file": r"kubejs\server_scripts\05_dark_magic_dimensions.js", "line": 145, "pattern": "narrative connection for Prompt 4"},
    {"file": r"kubejs\server_scripts\05_dark_magic_dimensions.js", "line": 179, "pattern": "Defined in Prompt 4's Draconic recipes"},
    # Cat 3
    {"file": r"kubejs\server_scripts\05_dark_magic_dimensions.js", "line": 162, "pattern": "Recipe removed per user request"},
    {"file": r"kubejs\server_scripts\07_draconic_endgame.js", "line": 40, "pattern": "Recipe removed per user request"},
    {"file": r"kubejs\server_scripts\21_fix_illusioner_crash.js", "line": 20, "pattern": "Log it so the user knows the fix is working"},
    {"file": r"kubejs\server_scripts\30_remove_create_sa_copper.js", "line": 3, "pattern": "The user wants to force the use of Ice and Fire's copper equipment"},
    {"file": r"kubejs\client_scripts\30_hide_create_sa_copper.js", "line": 3, "pattern": "The server removes these recipes to force the use of Ice and Fire"},
    {"file": r"kubejs\server_scripts\convert_chance.py", "line": 21, "pattern": "The user used"},
    {"file": r"kubejs\server_scripts\clean_suppressor.py", "line": 4, "pattern": "chris"},
    {"file": r"kubejs\server_scripts\fix_datapacks.py", "line": 6, "pattern": "chris"},
    {"file": r"kubejs\server_scripts\fix_fluid.py", "line": 2, "pattern": "chris"},
    {"file": r"kubejs\server_scripts\fix_transitional.py", "line": 8, "pattern": "transitionalItem"}
]

for c in PRIMARY_CITATIONS:
    p = os.path.join(MC_DIR, c["file"])
    exists = os.path.exists(p)
    matched = False
    actual_line_found = None
    line_content = None
    
    if exists:
        try:
            with open(p, "r", encoding="utf-8", errors="ignore") as f:
                f_lines = f.readlines()
            for idx, l in enumerate(f_lines, 1):
                if c["pattern"].lower() in l.lower():
                    matched = True
                    actual_line_found = idx
                    line_content = l.strip()
                    break
        except Exception as e:
            matched = False
            line_content = f"Error reading: {e}"
            
    res = {
        "file": c["file"],
        "expected_line": c["line"],
        "actual_line": actual_line_found,
        "pattern": c["pattern"],
        "exists": exists,
        "matched": matched,
        "line_content": line_content
    }
    audit_results["citations_tested"].append(res)
    if not exists or not matched:
        audit_results["citation_failures"].append(res)

# 3. Comprehensive KubeJS Scripts Verification (all 64 JS scripts)
actual_js_files = []
for root, dirs, files in os.walk(os.path.join(MC_DIR, "kubejs")):
    for f in files:
        if f.endswith(".js"):
            rel_path = os.path.relpath(os.path.join(root, f), MC_DIR)
            actual_js_files.append(rel_path)

audit_results["full_filesystem_census"]["total_kubejs_js_found"] = len(actual_js_files)
audit_results["full_filesystem_census"]["kubejs_js_list"] = sorted(actual_js_files)

# 4. Comprehensive Python scripts verification (all 24 py scripts)
actual_py_files = []
for root, dirs, files in os.walk(MC_DIR):
    for f in files:
        if f.endswith(".py"):
            rel_path = os.path.relpath(os.path.join(root, f), MC_DIR)
            actual_py_files.append(rel_path)

audit_results["full_filesystem_census"]["total_python_found"] = len(actual_py_files)
audit_results["full_filesystem_census"]["python_list"] = sorted(actual_py_files)

# 5. Quest Localization verification
quest_path = os.path.join(MC_DIR, "config", "ftbquests", "quests", "lang", "en_us.snbt")
if os.path.exists(quest_path):
    with open(quest_path, "r", encoding="utf-8", errors="ignore") as f:
        q_lines = f.readlines()
    audit_results["quest_verification"]["exists"] = True
    audit_results["quest_verification"]["line_count"] = len(q_lines)
    # Check sample quest subtitles
    sample_subtitles = [
        "Stab first. Ask questions never.",
        "Parry, lunge, finish.",
        "Two blades. One target. Zero survivors.",
        "If they can touch you, you're doing it wrong.",
        "conquer the 530-meal compendium",
        "free Waystone. You're a genius."
    ]
    subtitles_found = {}
    content_str = "".join(q_lines)
    for s in sample_subtitles:
        subtitles_found[s] = s.lower() in content_str.lower()
    audit_results["quest_verification"]["sample_subtitles_found"] = subtitles_found
else:
    audit_results["quest_verification"]["exists"] = False

# 6. Ore Report verification
ore_path = os.path.join(MC_DIR, "ore_report.md")
if os.path.exists(ore_path):
    with open(ore_path, "r", encoding="utf-8", errors="ignore") as f:
        o_lines = f.readlines()
    audit_results["ore_report_verification"]["exists"] = True
    audit_results["ore_report_verification"]["line_count"] = len(o_lines)
    audit_results["ore_report_verification"]["has_spanish_header"] = any("Reporte de Generación Original" in l for l in o_lines)
else:
    audit_results["ore_report_verification"]["exists"] = False

# 7. Empty directories check
empty_dirs = ["patchouli_books", "datapacks", "scripts", "resourcepacks"]
for ed in empty_dirs:
    ed_path = os.path.join(MC_DIR, ed)
    if os.path.exists(ed_path):
        contents = os.listdir(ed_path)
        audit_results["empty_dirs_verification"][ed] = {
            "exists": True,
            "is_empty": len(contents) == 0,
            "items": contents
        }
    else:
        audit_results["empty_dirs_verification"][ed] = {
            "exists": False,
            "is_empty": True,
            "items": []
        }

# 8. Verify Worker 1's artifacts
worker_all_files_json = os.path.join(WORKSPACE_ROOT, ".agents", "worker_1", "all_files_verification.json")
if os.path.exists(worker_all_files_json):
    with open(worker_all_files_json, "r", encoding="utf-8") as f:
        w_data = json.load(f)
    audit_results["worker_artifact_verification"]["all_files_json_count"] = len(w_data)
    audit_results["worker_artifact_verification"]["all_files_all_exist"] = all(item["exists"] for item in w_data)
    # Check if any file size/line count is dummy/zero
    zero_size = [item["relative_path"] for item in w_data if item["exists"] and item["size_bytes"] == 0]
    audit_results["worker_artifact_verification"]["zero_size_files"] = zero_size

# Output summary to console
print("================ INDEPENDENT AUDIT SUMMARY ================")
print(f"Deliverable Present: {audit_results['deliverable_present']} (Lines: {audit_results['deliverable_lines']}, Bytes: {audit_results['deliverable_size']})")
print(f"Total Primary Citations Tested: {len(audit_results['citations_tested'])}")
print(f"Citation Failures: {len(audit_results['citation_failures'])}")
print(f"KubeJS JS Files Found on Disk: {audit_results['full_filesystem_census']['total_kubejs_js_found']} (Report claims: 64)")
print(f"Python Files Found on Disk: {audit_results['full_filesystem_census']['total_python_found']} (Report claims: 24)")
print(f"Quest SNBT Exists: {audit_results['quest_verification']['exists']}, Lines: {audit_results['quest_verification'].get('line_count')} (Report claims: 3,310)")
print(f"Ore Report Exists: {audit_results['ore_report_verification']['exists']}, Lines: {audit_results['ore_report_verification'].get('line_count')} (Report claims: 144)")
print(f"Worker 1 Verified Files: {audit_results['worker_artifact_verification'].get('all_files_json_count')} (All exist: {audit_results['worker_artifact_verification'].get('all_files_all_exist')})")

with open(os.path.join(WORKSPACE_ROOT, ".agents", "auditor_1", "audit_empirical_results.json"), "w", encoding="utf-8") as f:
    json.dump(audit_results, f, indent=2)
