import os
import re
import json

KUBEJS_DIR = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\minecraft\kubejs"

KEYWORDS = [
    r"\bantigravity\b",
    r"\bchatgpt\b",
    r"\bopenai\b",
    r"\bgpt[-_ ]?\d*\b",
    r"\bclaude\b",
    r"\banthropic\b",
    r"\bcopilot\b",
    r"\bgemini\b",
    r"\bbard\b",
    r"\bllm\b",
    r"\bllama\b",
    r"\bdeepseek\b",
    r"\bqwen\b",
    r"\bmistral\b",
    r"\bollama\b",
    r"\bcursor\b",
    r"auto-generated",
    r"autogenerated",
    r"generated by",
    r"created by",
    r"created with",
    r"fixed by",
    r"prompt\s*\d*",
    r"certainly",
    r"here is",
    r"here's",
    r"as an ai",
    r"hope this helps",
    r"feel free",
    r"replace with",
    r"example usage",
    r"// ==========================================",
    r"PEAK EXPERT MODE",
    r"â€”",
    r"Ã¢â‚¬â€",
    r"Ã¢â€ â€™"
]

compiled_patterns = [(k, re.compile(k, re.IGNORECASE if not ("â" in k or "Ã" in k) else 0)) for k in KEYWORDS]

results = []
all_files_scanned = 0

for root, dirs, files in os.walk(KUBEJS_DIR):
    for f in files:
        ext = os.path.splitext(f)[1].lower()
        if ext in ['.js', '.json', '.txt', '.md', '.py', '.mcmeta']:
            all_files_scanned += 1
            full_path = os.path.join(root, f)
            try:
                with open(full_path, 'r', encoding='utf-8', errors='replace') as fp:
                    lines = fp.readlines()
            except Exception as e:
                continue

            file_matches = []
            for i, line in enumerate(lines, 1):
                for kw, pat in compiled_patterns:
                    m = pat.search(line)
                    if m:
                        file_matches.append({
                            "line": i,
                            "keyword": kw,
                            "content": line.strip()
                        })

            if file_matches:
                results.append({
                    "file": full_path,
                    "rel_file": os.path.relpath(full_path, KUBEJS_DIR),
                    "matches": file_matches
                })

out_path = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\.agents\explorer_1\scan_results.json"
with open(out_path, "w", encoding="utf-8") as out_fp:
    json.dump({"total_files": all_files_scanned, "results": results}, out_fp, indent=2)

print(f"Scanned {all_files_scanned} files. Found {len(results)} files with matches.")
