import os
import re
import json

ROOT_DIR = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\minecraft"

EXTENSIONS = {
    ".js", ".py", ".json", ".toml", ".txt", ".md", ".snbt", 
    ".zs", ".yaml", ".yml", ".properties", ".mcmeta", ".cfg", ".json5"
}

# Regex patterns for direct AI indicators and LLM markers
PATTERNS = [
    (r"(?i)\b(chatgpt|openai|claude|anthropic|gpt-[345]|copilot|gemini|deepseek|mistral|llama|ollama|aider|cursor|windsurf|antigravity)\b", "AI Model/Tool/Agent Mention"),
    (r"(?i)\b(prompt\s*\d+|user\s*prompt|system\s*prompt)\b", "Prompt Reference"),
    (r"(?i)(auto-generated by|generated by|created by ai|generated with ai|written by ai|fixed by ai|fixed by antigravity)", "AI Generation Disclosure"),
    (r"(?i)(as an ai|as a large language model|i have created|i have updated|here is the (code|script|updated|fixed))", "Conversational LLM Phrasing"),
    (r"(?i)\b(feel free to (change|tweak|adjust|modify)|adjust (these|the values|as needed))\b", "LLM Instruction Cliché"),
    (r"(Ã¢â‚¬â€|Ã¢â€ â€™|â€”|â†’)", "UTF-8 Mojibake from LLM Markdown/Unicode"),
    (r"```(javascript|js|json|toml|python|py)?", "Markdown Codeblock Fence"),
]

results = []

for dirpath, dirnames, filenames in os.walk(ROOT_DIR):
    # Skip git, mods jars, logs, cache, saves, screenshots, temp zips
    skip_dirs = {'.git', 'logs', 'crash-reports', 'cache', 'saves', 'screenshots', 'tmp_bc', 'tmp_bfb', 'tmp_cei', 'tmp_cna', 'tmp_irons', 'temp_alexscaves', 'temp_jar', 'temp_litho'}
    # Filter out skip_dirs in-place
    dirnames[:] = [d for d in dirnames if d not in skip_dirs and not d.startswith('.')]
    
    for fname in filenames:
        ext = os.path.splitext(fname)[1].lower()
        if ext not in EXTENSIONS:
            continue
        
        fpath = os.path.join(dirpath, fname)
        rel_path = os.path.relpath(fpath, ROOT_DIR)
        
        try:
            with open(fpath, 'r', encoding='utf-8', errors='replace') as f:
                lines = f.readlines()
        except Exception as e:
            continue
        
        file_matches = []
        for line_no, line in enumerate(lines, 1):
            line_str = line.strip()
            for pat, desc in PATTERNS:
                m = re.search(pat, line_str)
                if m:
                    # Filter false positives
                    matched_text = m.group(0)
                    # False positives filters:
                    if matched_text.lower() == 'gemini' and 'astral' in fpath.lower():
                        continue
                    if matched_text.lower() == 'cursor' and ('minecraft-cursor' in fpath or 'cursor' in line_str.lower()):
                        if 'minecraft_cursor' in line_str or 'remapCursors' in line_str or 'hover' in line_str or 'pointer' in line_str or 'crosshair' in line_str:
                            continue
                    if matched_text.lower() == 'antigravity' and 'irons_spellbooks' in line_str:
                        continue
                    if 'generated by' in matched_text.lower() and ('mod' in line_str.lower() or 'game' in line_str.lower() or 'player' in line_str.lower() or 'generator' in line_str.lower() or 'structure' in line_str.lower()):
                        if not any(x in line_str.lower() for x in ['antigravity', 'ai', 'chatgpt', 'claude', 'prompt']):
                            continue
                    file_matches.append({
                        "line": line_no,
                        "match_type": desc,
                        "matched": matched_text,
                        "content": line_str[:150]
                    })
        
        if file_matches:
            results.append({
                "file": fpath,
                "rel_path": rel_path,
                "total_lines": len(lines),
                "matches": file_matches
            })

with open(r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\.agents\explorer_3\scan_results.json", 'w', encoding='utf-8') as out_f:
    json.dump(results, out_f, indent=2)

print(f"Scanned complete. Found {len(results)} files with matches.")
