import os
import json

base_dir = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\minecraft"

files_to_verify = [
    # Category A: Explicit Antigravity / AI Disclosures
    ("kubejs/server_scripts/00_tags.js", 1, "// Auto-generated by Antigravity: Tag unifications"),
    ("kubejs/server_scripts/20_fixed_datapacks.js", 1, "// Auto-generated by Antigravity to fix broken datapack recipes"),
    ("kubejs/server_scripts/convert_to_js.py", 9, "f_out.write(\"// Auto-generated by Antigravity to fix broken datapack recipes\\n\")"),
    ("kubejs/assets/minecraft/models/block/flowerbed_1.json", 2, "\"credit\": \"Made with Blockbench / Fixed by Antigravity\""),
    ("kubejs/assets/minecraft/models/block/flowerbed_2.json", 2, "\"credit\": \"Made with Blockbench / Fixed by Antigravity\""),
    ("kubejs/assets/minecraft/models/block/flowerbed_3.json", 2, "\"credit\": \"Made with Blockbench / Fixed by Antigravity\""),
    ("kubejs/assets/minecraft/models/block/flowerbed_4.json", 2, "\"credit\": \"Made with Blockbench / Fixed by Antigravity\""),
    ("check_client_toml.py", 8, "# List from user prompt"),
    
    # Category B: Explicit Prompt references
    ("kubejs/server_scripts/expert_mode_recipes.js", 65, "//  to use Create components - handled in prompt 2)"),
    ("kubejs/server_scripts/03_pneumatic_mekanism_gates.js", 298, "// Note: This will be further refined in Prompt 4"),
    ("kubejs/server_scripts/03_pneumatic_mekanism_gates.js", 311, "// Will be fully defined in Prompt 4 (needs AE2 components)"),
    ("kubejs/server_scripts/05_dark_magic_dimensions.js", 145, "// This is mostly a narrative connection for Prompt 4"),
    ("kubejs/server_scripts/05_dark_magic_dimensions.js", 179, "// (Defined in Prompt 4's Draconic recipes)"),
]

all_verified = True
verification_log = []

for rel, expected_line, expected_snip in files_to_verify:
    full_path = os.path.normpath(os.path.join(base_dir, rel))
    exists = os.path.exists(full_path)
    if not exists:
        all_verified = False
        verification_log.append(f"FAIL: File does not exist: {full_path}")
        continue
    
    with open(full_path, 'r', encoding='utf-8', errors='replace') as f:
        lines = f.readlines()
    
    # Verify line content
    if expected_line <= len(lines):
        actual_line_content = lines[expected_line - 1].strip()
        has_snippet = expected_snip.lower() in actual_line_content.lower() or expected_snip in actual_line_content
        verification_log.append({
            "rel_path": rel,
            "abs_path": full_path,
            "exists": True,
            "total_lines": len(lines),
            "checked_line": expected_line,
            "content": actual_line_content,
            "match": has_snippet
        })
    else:
        verification_log.append(f"FAIL: Line {expected_line} out of range ({len(lines)} lines)")

with open(r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\.agents\explorer_3\verification_results.json", 'w', encoding='utf-8') as out:
    json.dump(verification_log, out, indent=2)

print(f"Verification complete. All checked files exist: {all_verified}")
