import os
import re

ROOT_DIR = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\minecraft"

# 1. Test citations from Category 1, 2, 3
citations_to_check = [
    # Category 1
    (r"kubejs\server_scripts\00_tags.js", 1, "Auto-generated by Antigravity: Tag unifications"),
    (r"kubejs\server_scripts\20_fixed_datapacks.js", 1, "Auto-generated by Antigravity to fix broken datapack recipes"),
    (r"kubejs\server_scripts\convert_to_js.py", 9, "Auto-generated by Antigravity to fix broken datapack recipes"),
    (r"kubejs\assets\minecraft\models\block\flowerbed_1.json", 2, "Made with Blockbench / Fixed by Antigravity"),
    (r"kubejs\assets\minecraft\models\block\flowerbed_2.json", 2, "Made with Blockbench / Fixed by Antigravity"),
    (r"kubejs\assets\minecraft\models\block\flowerbed_3.json", 2, "Made with Blockbench / Fixed by Antigravity"),
    (r"kubejs\assets\minecraft\models\block\flowerbed_4.json", 2, "Made with Blockbench / Fixed by Antigravity"),
    (r"check_client_toml.py", 8, "# List from user prompt"),
    (r"generate_high_priority_data.py", 47, "Archivo generado"),
    (r"scratch\mod_extraction\convert_recipes.py", 97, "Archivo generado"),
    # Category 2
    (r"kubejs\server_scripts\expert_mode_recipes.js", 65, "handled in prompt 2"),
    (r"kubejs\server_scripts\03_pneumatic_mekanism_gates.js", 298, "further refined in Prompt 4"),
    (r"kubejs\server_scripts\03_pneumatic_mekanism_gates.js", 311, "fully defined in Prompt 4"),
    (r"kubejs\server_scripts\05_dark_magic_dimensions.js", 145, "narrative connection for Prompt 4"),
    (r"kubejs\server_scripts\05_dark_magic_dimensions.js", 179, "Defined in Prompt 4's Draconic recipes"),
    # Category 3
    (r"kubejs\server_scripts\05_dark_magic_dimensions.js", 162, "Recipe removed per user request"),
    (r"kubejs\server_scripts\07_draconic_endgame.js", 40, "Recipe removed per user request"),
    (r"kubejs\server_scripts\21_fix_illusioner_crash.js", 20, "Log it so the user knows the fix is working"),
    (r"kubejs\server_scripts\30_remove_create_sa_copper.js", 3, "The user wants to force the use of Ice and Fire's copper equipment"),
    (r"kubejs\client_scripts\30_hide_create_sa_copper.js", 3, "The server removes these recipes to force the use of Ice and Fire"),
    (r"kubejs\server_scripts\convert_chance.py", 21, "The user used"),
    (r"kubejs\server_scripts\clean_suppressor.py", 4, r"c:\Users\chris\AppData\Roaming\PrismLauncher\instances\PEAK-dev"),
    (r"kubejs\server_scripts\fix_datapacks.py", 6, r"c:\Users\chris\AppData\Roaming\PrismLauncher\instances\PEAK-dev"),
    (r"kubejs\server_scripts\fix_fluid.py", 2, r"c:\Users\chris\AppData\Roaming\PrismLauncher\instances\PEAK-dev"),
    (r"kubejs\server_scripts\fix_transitional.py", 8, "transitionalItem"),
]

print("=== CITATIONS CHECK ===")
for rel_path, expected_line, pattern in citations_to_check:
    full_path = os.path.join(ROOT_DIR, rel_path)
    if not os.path.exists(full_path):
        print(f"[MISSING FILE] {rel_path}")
        continue
    with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()
    
    # Check exact or near line
    found = False
    for idx, line in enumerate(lines, 1):
        if pattern.lower() in line.lower():
            diff = abs(idx - expected_line)
            status = "EXACT" if diff == 0 else f"OFFSET ({idx} vs cited {expected_line})"
            print(f"[OK - {status}] {rel_path}: '{pattern}' at line {idx}")
            found = True
            break
    if not found:
        print(f"[FAIL PATTERN NOT FOUND] {rel_path}: '{pattern}'")

# 2. Check 64 KubeJS scripts table in Section 5.2
print("\n=== KUBEJS SCRIPTS INVENTORY CHECK ===")
js_table_files = [
    r"kubejs/server_scripts/00_recipe_fixer.js",
    r"kubejs/server_scripts/00_tags.js",
    r"kubejs/server_scripts/02_create_era_gates.js",
    r"kubejs/server_scripts/03_pneumatic_mekanism_gates.js",
    r"kubejs/server_scripts/04_magic_integration.js",
    r"kubejs/server_scripts/05_dark_magic_dimensions.js",
    r"kubejs/server_scripts/06_enderio_ae2.js",
    r"kubejs/server_scripts/07_draconic_endgame.js",
    r"kubejs/server_scripts/08_reliquary_balance.js",
    r"kubejs/server_scripts/09_custom_loot_tables.js",
    r"kubejs/server_scripts/10_avaritia_final_polish.js",
    r"kubejs/server_scripts/11_end_gating.js",
    r"kubejs/server_scripts/12_admin_commands.js",
    r"kubejs/server_scripts/12_food_buffs.js",
    r"kubejs/server_scripts/13_simply_mythics_loot.js",
    r"kubejs/server_scripts/13a_food_overhaul_farmersdelight.js",
    r"kubejs/server_scripts/13b_food_overhaul_dimensions.js",
    r"kubejs/server_scripts/13c_food_overhaul_creatures.js",
    r"kubejs/server_scripts/13d_food_overhaul_magic.js",
    r"kubejs/server_scripts/13e_food_fixes.js",
    r"kubejs/server_scripts/14_waystone_balance.js",
    r"kubejs/server_scripts/15_loot_nerfs.js",
    r"kubejs/server_scripts/16_recipes_and_balance.js",
    r"kubejs/server_scripts/17_goblin_trades.js",
    r"kubejs/server_scripts/18_boss_duplicator.js",
    r"kubejs/server_scripts/19_mob_gear.js",
    r"kubejs/server_scripts/20_disable_bugged_spells.js",
    r"kubejs/server_scripts/20_disable_bugged_spells_data.js",
    r"kubejs/server_scripts/20_fixed_datapacks.js",
    r"kubejs/server_scripts/21_backpack_upgrades.js",
    r"kubejs/server_scripts/21_fix_illusioner_crash.js",
    r"kubejs/server_scripts/22_apotheosis_gear_sets.js",
    r"kubejs/server_scripts/23_fix_illager_weapons.js",
    r"kubejs/server_scripts/23_zenith_saber.js",
    r"kubejs/server_scripts/24_pixie_spawn_limiter.js",
    r"kubejs/server_scripts/25_hardcoded_minibosses.js",
    r"kubejs/server_scripts/26_mob_max_health_fix.js",
    r"kubejs/server_scripts/30_remove_create_sa_copper.js",
    r"kubejs/server_scripts/32_ban_raid_blimp.js",
    r"kubejs/server_scripts/33_remove_vampirism_coatings.js",
    r"kubejs/server_scripts/34_ban_ender_eye.js",
    r"kubejs/server_scripts/41_iaf_loot_buff.js",
    r"kubejs/server_scripts/50_xp_fluids_unification.js",
    r"kubejs/server_scripts/60_dragonforge_materials.js",
    r"kubejs/server_scripts/61_spellbook_assembly.js",
    r"kubejs/server_scripts/apotheosis_auto_tiers.js",
    r"kubejs/server_scripts/dump_ids.js",
    r"kubejs/server_scripts/expert_mode_recipes.js",
    r"kubejs/server_scripts/fix_illusioner_crash.js",
    r"kubejs/server_scripts/nerf_irons_jewelry.js",
    r"kubejs/client_scripts/14_translations.js",
    r"kubejs/client_scripts/30_hide_create_sa_copper.js",
    r"kubejs/client_scripts/32_hide_raid_blimp.js",
    r"kubejs/client_scripts/35_hide_technical_items.js",
    r"kubejs/client_scripts/36_hide_incomplete_items.js",
    r"kubejs/client_scripts/37_hide_banned_and_disabled_items.js",
    r"kubejs/client_scripts/main.js",
    r"kubejs/startup_scripts/14_waystone_balance.js",
    r"kubejs/startup_scripts/40_iaf_durability_buff.js",
    r"kubejs/startup_scripts/50_avarice_swords_damage.js",
    r"kubejs/startup_scripts/60_spellbook_rebalance.js",
    r"kubejs/startup_scripts/custom_items.js",
    r"kubejs/startup_scripts/fix_malum_watchdog.js",
    r"kubejs/startup_scripts/main.js"
]

all_kubejs_js = []
for root, dirs, files in os.walk(os.path.join(ROOT_DIR, "kubejs")):
    for f in files:
        if f.endswith(".js"):
            all_kubejs_js.append(os.path.relpath(os.path.join(root, f), ROOT_DIR).replace("\\", "/"))

print(f"Total JS files in table: {len(js_table_files)}")
print(f"Total JS files in filesystem: {len(all_kubejs_js)}")
missing_in_fs = set(js_table_files) - set(all_kubejs_js)
extra_in_fs = set(all_kubejs_js) - set(js_table_files)
print(f"Missing in filesystem: {missing_in_fs}")
print(f"Extra in filesystem: {extra_in_fs}")

# 3. Check Python scripts table in Section 6.1
print("\n=== PYTHON SCRIPTS INVENTORY CHECK ===")
py_table_files = [
    r"check_client_toml.py",
    r"check_mods.py",
    r"check_shine.py",
    r"check_specific.py",
    r"deep_check.py",
    r"find_recipes.py",
    r"fix_fluids.py",
    r"fix_json.py",
    r"fix_suppressor.py",
    r"fix_syntax.py",
    r"fix_syntax_errors.py",
    r"generate_dummy_recipes.py",
    r"generate_high_priority_data.py",
    r"generate_physical_datapack.py",
    r"get_missing_items.py",
    r"replace_missing_items.py",
    r"rewrite_20_fixed_datapacks.py",
    r"kubejs/server_scripts/clean_suppressor.py",
    r"kubejs/server_scripts/convert_chance.py",
    r"kubejs/server_scripts/convert_to_js.py",
    r"kubejs/server_scripts/fix_datapacks.py",
    r"kubejs/server_scripts/fix_fluid.py",
    r"kubejs/server_scripts/fix_transitional.py",
    r"scratch/mod_extraction/convert_recipes.py"
]

all_py = []
for root, dirs, files in os.walk(ROOT_DIR):
    for f in files:
        if f.endswith(".py"):
            all_py.append(os.path.relpath(os.path.join(root, f), ROOT_DIR).replace("\\", "/"))

print(f"Total Python files in table: {len(py_table_files)}")
print(f"Total Python files in filesystem: {len(all_py)}")
missing_py = set(py_table_files) - set(all_py)
extra_py = set(all_py) - set(py_table_files)
print(f"Missing in filesystem: {missing_py}")
print(f"Extra in filesystem: {extra_py}")
