"""
Tier 2: Boundary & Corner Cases Test Suite.
Verifies edge cases, non-ASCII handling, multiline structures, and stress conditions:
- Case-insensitive regex variations for banned AI terms
- Multiline comment blocks and embedded comments
- Non-ASCII and mojibake resilience
- Empty files and minimal scripts
- JSON structural integrity edge cases
"""
from pathlib import Path
import unittest

from tests.helpers.js_validator import JSValidator
from tests.helpers.json_validator import JSONValidator
from tests.helpers.regex_scanner import RegexScanner


class TestTier2BoundaryCases(unittest.TestCase):
    def setUp(self):
        self.scanner = RegexScanner()
        self.js_validator = JSValidator()
        self.json_validator = JSONValidator()

    def test_01_case_insensitive_regex_variations(self):
        """Verify that all casing permutations of banned terms are detected."""
        test_samples = [
            ("aNtIgRaViTy is here", "AI_AGENT_ANTIGRAVITY"),
            ("ANTIGRAVITY: Tag unifications", "AI_AGENT_ANTIGRAVITY"),
            ("chatgpt generated this", "AI_MODELS_CHATGPT_CLAUDE"),
            ("OPENAI helper routine", "AI_MODELS_CHATGPT_CLAUDE"),
            ("Claude 3.5 Sonnet", "AI_MODELS_CHATGPT_CLAUDE"),
            ("handled in PROMPT 2", "AI_PROMPT_ITERATION"),
            ("defined in prompt   4", "AI_PROMPT_ITERATION"),
            ("AUTO-GENERATED BY AI", "AI_AUTOGEN_HEADER"),
            ("FIXED BY ANTIGRAVITY", "AI_FIXED_BY"),
            ("PER USER REQUEST", "AI_USER_REQUEST_CONVERSATION"),
            ("THE USER WANTS TO force Ice and Fire", "AI_USER_REQUEST_CONVERSATION"),
            ("ARCHIVO GENERADO AUTOMÁTICAMENTE", "AI_SPANISH_AUTOGEN"),
            ("archivo generado automaticamente", "AI_SPANISH_AUTOGEN"),
            ("C:\\Users\\chris\\AppData\\Roaming\\PrismLauncher", "DEV_ABSOLUTE_PATH_LEAKAGE"),
            ("c:\\users\\wamb9\\desktop\\temp", "DEV_ABSOLUTE_PATH_LEAKAGE"),
        ]

        for text, expected_rule_id in test_samples:
            violations = self.scanner.scan_text(text)
            rule_ids = [v.rule_id for v in violations]
            self.assertIn(
                expected_rule_id,
                rule_ids,
                f"Failed to detect rule {expected_rule_id} in sample: '{text}' (found: {rule_ids})",
            )

    def test_02_whitelist_preservation_for_ingame_antigravity(self):
        """Verify that legitimate in-game status effect identifiers are not flagged as violations."""
        clean_samples = [
            "event.add('irons_spellbooks:antigravity')",
            "effect.irons_spellbooks.antigravity=Antigravity",
            "mob.addEffect('irons_spellbooks:antigravity', 200, 1)",
        ]

        for text in clean_samples:
            violations = self.scanner.scan_text(text)
            self.assertEqual(
                len(violations),
                0,
                f"Legitimate in-game effect falsely flagged: {violations}",
            )

    def test_03_multiline_and_block_comment_handling(self):
        """Verify that comments embedded inside multiline block comments are detected and handled."""
        multiline_js = """
        /*
         * Auto-generated by Antigravity to fix broken datapack recipes
         * Staged for Prompt 4 integration
         */
        ServerEvents.recipes(event => {
            /* Handled in prompt 2 */
            event.shaped('minecraft:stone', ['AAA', 'AAA', 'AAA'], { A: 'minecraft:dirt' });
        });
        """
        violations = self.scanner.scan_text(multiline_js)
        self.assertGreaterEqual(len(violations), 3, f"Expected at least 3 violations in block comments, got {len(violations)}")

        # Verify comment stripper cleans both block and inline comments without affecting code
        clean_code = self.js_validator.strip_comments(multiline_js)
        self.assertNotIn("Auto-generated", clean_code)
        self.assertNotIn("Prompt 4", clean_code)
        self.assertNotIn("prompt 2", clean_code)
        self.assertIn("ServerEvents.recipes", clean_code)
        self.assertIn("event.shaped", clean_code)

    def test_04_comments_inside_string_literals_are_not_stripped(self):
        """Verify that URL strings or text containing '//' or '/*' inside quotes are preserved."""
        code_with_strings = """
        let url = "https://example.com/api/test";
        let regex_str = '/* not a comment */';
        let template_str = `// not a comment either ${1 + 1}`;
        """
        clean_code = self.js_validator.strip_comments(code_with_strings)
        self.assertIn("https://example.com/api/test", clean_code)
        self.assertIn("/* not a comment */", clean_code)
        self.assertIn("// not a comment either", clean_code)

    def test_05_non_ascii_and_unicode_emoji_resilience(self):
        """Verify that non-ASCII characters, mojibake, and emojis do not crash validators or tokenizers."""
        unicode_js = """
        // Header with em-dash and emojis: PEAK EXPERT MODE — 🌟⚔️🔮
        console.log('[PEAK] Script 01: 🍞 Cuisine & Forging â€” ACTIVE! â†’');
        ServerEvents.tags('item', event => {
            event.add('c:tools/wrench', 'create:wrench');
        });
        """
        # Tokenizer extraction
        tokens = self.js_validator.extract_functional_tokens(unicode_js)
        self.assertIn("console", tokens)
        self.assertIn("ServerEvents", tokens)
        self.assertIn("create:wrench", " ".join(tokens))

        # Syntax check via Node
        valid, err = self.js_validator.check_syntax_string_node(unicode_js)
        self.assertTrue(valid, f"Unicode JS syntax check failed: {err}")

    def test_06_empty_file_and_whitespace_only_handling(self):
        """Verify that 0-byte or whitespace-only files pass safely without exceptions."""
        empty_str = ""
        whitespace_str = "   \n\t  \n  "

        self.assertEqual(len(self.scanner.scan_text(empty_str)), 0)
        self.assertEqual(len(self.scanner.scan_text(whitespace_str)), 0)
        self.assertEqual(len(self.js_validator.extract_functional_tokens(empty_str)), 0)
        self.assertEqual(len(self.js_validator.extract_functional_tokens(whitespace_str)), 0)

    def test_07_json_structure_integrity_detection(self):
        """Verify that JSONValidator properly identifies syntax and structure errors."""
        bad_jsons = [
            ("{ key: 'value' }", "Unquoted key"),
            ('{"key": "value",}', "Trailing comma"),
            ('{"key": [1, 2, 3}', "Unclosed bracket"),
            ('{"credit": "Made with Blockbench", "ambientocclusion": }', "Missing value"),
        ]
        for bad_json_str, desc in bad_jsons:
            # Test direct parsing
            valid, err, _ = self.json_validator.validate_file(Path("non_existent_file.json"))
            self.assertFalse(valid)


if __name__ == "__main__":
    unittest.main()
