import os
import re
import json

minecraft_dir = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\minecraft"

# Test all tables and claims in ai_audit_report.md
citations = [
    # Table 2.1 (Explicit AI Branding)
    {"file": r"kubejs\server_scripts\00_tags.js", "line": 1, "pattern": "// Auto-generated by Antigravity: Tag unifications"},
    {"file": r"kubejs\server_scripts\20_fixed_datapacks.js", "line": 1, "pattern": "// Auto-generated by Antigravity to fix broken datapack recipes"},
    {"file": r"kubejs\server_scripts\convert_to_js.py", "line": 9, "pattern": 'f_out.write("// Auto-generated by Antigravity to fix broken datapack recipes\\n")'},
    {"file": r"kubejs\assets\minecraft\models\block\flowerbed_1.json", "line": 2, "pattern": '"credit": "Made with Blockbench / Fixed by Antigravity",'},
    {"file": r"kubejs\assets\minecraft\models\block\flowerbed_2.json", "line": 2, "pattern": '"credit": "Made with Blockbench / Fixed by Antigravity",'},
    {"file": r"kubejs\assets\minecraft\models\block\flowerbed_3.json", "line": 2, "pattern": '"credit": "Made with Blockbench / Fixed by Antigravity",'},
    {"file": r"kubejs\assets\minecraft\models\block\flowerbed_4.json", "line": 2, "pattern": '"credit": "Made with Blockbench / Fixed by Antigravity",'},
    {"file": r"check_client_toml.py", "line": 8, "pattern": "# List from user prompt"},
    {"file": r"generate_high_priority_data.py", "line": 47, "pattern": 'out.write("// Archivo generado automáticamente para sobrescribir JSONs rotos de los mods.\\n")'},
    {"file": r"scratch\mod_extraction\convert_recipes.py", "line": 97, "pattern": 'out.write("// Archivo generado automáticamente para corregir las recetas rotas de Create en 1.21.1\\n")'},

    # Table 3.1 (Multi-Prompt Staged Generation)
    {"file": r"kubejs\server_scripts\expert_mode_recipes.js", "line": 65, "pattern": "handled in prompt 2"},
    {"file": r"kubejs\server_scripts\03_pneumatic_mekanism_gates.js", "line": 298, "pattern": "Note: This will be further refined in Prompt 4"},
    {"file": r"kubejs\server_scripts\03_pneumatic_mekanism_gates.js", "line": 311, "pattern": "Will be fully defined in Prompt 4 (needs AE2 components)"},
    {"file": r"kubejs\server_scripts\05_dark_magic_dimensions.js", "line": 145, "pattern": "This is mostly a narrative connection for Prompt 4"},
    {"file": r"kubejs\server_scripts\05_dark_magic_dimensions.js", "line": 179, "pattern": "(Defined in Prompt 4's Draconic recipes)"},

    # Table 4.1 (Interactive Dialogue & User Request Residue)
    {"file": r"kubejs\server_scripts\05_dark_magic_dimensions.js", "line": 162, "pattern": "// (Recipe removed per user request)"},
    {"file": r"kubejs\server_scripts\07_draconic_endgame.js", "line": 40, "pattern": "// (Recipe removed per user request)"},
    {"file": r"kubejs\server_scripts\21_fix_illusioner_crash.js", "line": 20, "pattern": "// Log it so the user knows the fix is working"},
    {"file": r"kubejs\server_scripts\30_remove_create_sa_copper.js", "line": 3, "pattern": "// The user wants to force the use of Ice and Fire's copper equipment because it is better balanced."},
    {"file": r"kubejs\client_scripts\30_hide_create_sa_copper.js", "line": 3, "pattern": "// The server removes these recipes to force the use of Ice and Fire's better balanced copper equipment."},
    {"file": r"kubejs\server_scripts\convert_chance.py", "line": 20, "pattern": "The user used {fluidTag: 'c:milk', amount: 250.0}"},
    {"file": r"kubejs\server_scripts\clean_suppressor.py", "line": 4, "pattern": "chris"},
    {"file": r"kubejs\server_scripts\fix_datapacks.py", "line": 6, "pattern": "chris"},
    {"file": r"kubejs\server_scripts\fix_fluid.py", "line": 2, "pattern": "chris"},
    {"file": r"kubejs\server_scripts\fix_transitional.py", "line": 8, "pattern": "transitionalItem"},
]

results = []
all_passed = True
for c in citations:
    fpath = os.path.join(minecraft_dir, c["file"])
    if not os.path.exists(fpath):
        results.append({"citation": c, "status": "FAIL_FILE_NOT_FOUND"})
        all_passed = False
        continue
    with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()
    
    # Check exact line (1-indexed) or within +/- 3 lines
    target_line_idx = c["line"] - 1
    found_line = None
    exact_line_match = False
    
    if 0 <= target_line_idx < len(lines):
        if c["pattern"].lower() in lines[target_line_idx].lower():
            exact_line_match = True
            found_line = c["line"]

    if not exact_line_match:
        # Search all lines
        for idx, l in enumerate(lines):
            if c["pattern"].lower() in l.lower():
                found_line = idx + 1
                break

    if found_line:
        results.append({
            "file": c["file"],
            "expected_line": c["line"],
            "found_line": found_line,
            "exact_line": (found_line == c["line"]),
            "status": "PASS",
            "pattern": c["pattern"]
        })
    else:
        results.append({
            "file": c["file"],
            "expected_line": c["line"],
            "status": "FAIL_PATTERN_NOT_FOUND",
            "pattern": c["pattern"]
        })
        all_passed = False

print(f"Total citations tested: {len(citations)}")
pass_count = sum(1 for r in results if r["status"] == "PASS")
print(f"Passed: {pass_count}/{len(citations)}")
for r in results:
    if r["status"] != "PASS" or not r.get("exact_line", True):
        print(f"Mismatch or fail: {r}")
