import re

dump_file = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\.agents\explorer_survey_2\all_comments_dump.txt"

with open(dump_file, 'r', encoding='utf-8') as f:
    lines = f.readlines()

patterns = [
    (r'\bantigravity\b', 'Antigravity keyword'),
    (r'\bchatgpt\b|\bgpt\b|\bclaude\b|\bgemini\b|\bopenai\b|\bllm\b', 'LLM / AI keyword'),
    (r'\bprompt\b', 'Prompt keyword'),
    (r'auto-generated|autogenerated|generated by', 'Auto-generation marker'),
    (r'fixed by', 'Fixed-by attribution'),
    (r'\buser\b', 'User reference'),
    (r'\brequest\b|\brequested\b', 'Request reference'),
    (r'\bper\s+(?:the\s+)?(?:user|request|instructions|prompt)', 'Per user/request pattern'),
    (r'\bi\s+(?:have|noticed|will|should|must|added|removed|changed|fixed|am|think)\b', 'First-person singular AI artifact'),
    (r'\bwe\s+(?:need|should|decided|will|have|want|can|must)\b', 'First-person plural conversational artifact'),
    (r'\bas\s+requested\b', 'As requested pattern'),
    (r'\blet\'?s\b', "Let's conversational pattern"),
    (r'\bwait\b', 'Wait conversational pattern'),
    (r'\bnote:\s*this\b|\bnote:\s*we\b|\bnote:\s*i\b', 'Conversational Note pattern'),
    (r'\binstruction\b|\binstructions\b', 'Instruction pattern'),
]

matched_lines = set()
results = []

for idx, line in enumerate(lines):
    for pat, label in patterns:
        if re.search(pat, line, re.IGNORECASE):
            results.append((line.strip(), label))
            matched_lines.add(idx)

print(f"Total matching comments: {len(results)}")
for line, label in results:
    print(f"[{label}] {line}")
