import os

kubejs_dir = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\minecraft\kubejs"

files_summary = []

flagged_files = {
    r"server_scripts\00_tags.js": [
        (1, "// Auto-generated by Antigravity: Tag unifications", "AI Attribution Header", "Replace with clean comment '// Tag unifications' or delete line")
    ],
    r"server_scripts\03_pneumatic_mekanism_gates.js": [
        (298, "    // Note: This will be further refined in Prompt 4", "Prompt Iteration Marker", "Delete line cleanly"),
        (311, "    // Will be fully defined in Prompt 4 (needs AE2 components)", "Prompt Iteration Marker", "Replace lines 311-312 with neutral comment or delete cleanly")
    ],
    r"server_scripts\05_dark_magic_dimensions.js": [
        (145, "    // This is mostly a narrative connection for Prompt 4", "Prompt Iteration Marker", "Delete line or remove unused comment block"),
        (162, "    // (Recipe removed per user request)", "User Dialogue Remnant", "Delete lines 161-163 cleanly"),
        (179, "    // (Defined in Prompt 4's Draconic recipes)", "Prompt Iteration Marker", "Replace with '(Defined in Draconic recipes)' or delete line")
    ],
    r"server_scripts\07_draconic_endgame.js": [
        (40, "    // (Recipe removed per user request)", "User Dialogue Remnant", "Delete lines 39-43 cleanly")
    ],
    r"server_scripts\20_fixed_datapacks.js": [
        (1, "// Auto-generated by Antigravity to fix broken datapack recipes", "AI Attribution Header", "Replace with '// Datapack recipe overrides and fixes' or delete line")
    ],
    r"server_scripts\21_fix_illusioner_crash.js": [
        (20, "        // Log it so the user knows the fix is working", "Conversational User Reference", "Replace with '// Log weapon correction to confirm event handling' or delete line")
    ],
    r"server_scripts\30_remove_create_sa_copper.js": [
        (3, "    // The user wants to force the use of Ice and Fire's copper equipment because it is better balanced.", "Conversational User Reference", "Replace lines 3-4 with neutral design comment or delete lines")
    ],
    r"server_scripts\expert_mode_recipes.js": [
        (65, "    //  to use Create components - handled in prompt 2)", "Prompt Iteration Marker", "Replace line 65 with '    //  to use Create components)' or delete lines 62-66")
    ]
}

for root, dirs, files in sorted(os.walk(kubejs_dir)):
    for f in sorted(files):
        if f.endswith('.js'):
            full_path = os.path.join(root, f)
            rel_path = os.path.relpath(full_path, kubejs_dir)
            with open(full_path, 'r', encoding='utf-8', errors='ignore') as fo:
                lines = fo.readlines()
            
            line_count = len(lines)
            status = "CONTAMINATED" if rel_path in flagged_files else "CLEAN"
            issues = flagged_files.get(rel_path, [])
            files_summary.append({
                'rel_path': rel_path,
                'line_count': line_count,
                'status': status,
                'issue_count': len(issues),
                'issues': issues
            })

print(f"Total files audited: {len(files_summary)}")
clean_count = sum(1 for x in files_summary if x['status'] == 'CLEAN')
contam_count = sum(1 for x in files_summary if x['status'] == 'CONTAMINATED')
print(f"Clean files: {clean_count}")
print(f"Contaminated files: {contam_count}")
print(f"Total AI indicators identified: {sum(x['issue_count'] for x in files_summary)}")
