import re

dump_file = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\.agents\explorer_survey_2\all_comments_dump.txt"

with open(dump_file, 'r', encoding='utf-8') as f:
    comments = f.readlines()

print(f"Total comments in corpus: {len(comments)}")

# Let's search for specific suspicious patterns
suspicious = []
for c in comments:
    # Check for any variation
    lower = c.lower()
    
    # 1. Direct AI/LLM
    if any(k in lower for k in ['antigravity', 'chatgpt', 'gpt', 'openai', 'claude', 'gemini', 'copilot', 'llm', 'prompt', 'per user', 'user wants', 'user request', 'user asked', 'user requested']):
        suspicious.append(('CRITICAL_AI_VIOLATION', c.strip()))
    
    # 2. Conversational dialogue remnants
    elif any(k in lower for k in ['as requested', 'per request', 'per instructions', 'the user', 'so the user knows', 'handled in', 'defined in prompt', 'narrative connection']):
        suspicious.append(('CONVERSATIONAL_REMNANT', c.strip()))
        
    # 3. First person reasoning
    elif any(k in lower for k in ['i noticed', 'i fixed', 'i decided', 'i added', 'i changed', 'i will', 'wait,', 'let\'s see', 'we decided', 'we should note']):
        suspicious.append(('FIRST_PERSON_REASONING', c.strip()))
        
    # 4. Auto-generated / Fixed by
    elif any(k in lower for k in ['auto-generated', 'autogenerated', 'fixed by']):
        suspicious.append(('ATTRIBUTION_HEADER', c.strip()))

print(f"\nFound {len(suspicious)} items:")
for cat, item in suspicious:
    print(f"[{cat}] {item}")
