import os
import re

kubejs_dir = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\minecraft\kubejs"

keywords = [
    r'\bantigravity\b',
    r'\bchatgpt\b',
    r'\bopenai\b',
    r'\bclaude\b',
    r'\bgemini\b',
    r'\bcopilot\b',
    r'\bllm\b',
    r'\bprompt',
    r'\bauto-generated\b',
    r'\bautogenerated\b',
    r'\bfixed by\b',
    r'\bper user\b',
    r'\buser wants\b',
    r'\buser request\b',
    r'\buser asked\b',
    r'\buser requested\b',
    r'so the user knows',
    r'wait,\s*kubejs',
    r'handled in prompt',
    r'defined in prompt',
    r'connection for prompt',
    r'\bassistant\b',
    r'\bmodel\b',
    r'\bsession\b',
]

results = []

for root, dirs, files in sorted(os.walk(kubejs_dir)):
    for f in sorted(files):
        if f.endswith('.js'):
            filepath = os.path.join(root, f)
            rel_path = os.path.relpath(filepath, kubejs_dir)
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as file_obj:
                for idx, line in enumerate(file_obj):
                    for kw in keywords:
                        if re.search(kw, line, re.IGNORECASE):
                            results.append({
                                'file': rel_path,
                                'line': idx + 1,
                                'pattern': kw,
                                'content': line.rstrip()
                            })

print(f"Total matching lines across JS files: {len(results)}")
for r in results:
    print(f"[{r['file']}:{r['line']}] ({r['pattern']})\n  {r['content']}")
