import os
import re

kubejs_dir = r"c:\Users\wamb9\MINECRAFT\Prism\Instances\PEAK dev\minecraft\kubejs"

js_files = []
for root, dirs, files in os.walk(kubejs_dir):
    for f in files:
        if f.endswith('.js'):
            js_files.append(os.path.join(root, f))

print(f"Total JS files found: {len(js_files)}")

# Let's inspect all comments in each JS file
findings = []

for filepath in sorted(js_files):
    rel_path = os.path.relpath(filepath, kubejs_dir)
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        lines = f.readlines()
    
    for idx, line in enumerate(lines):
        line_num = idx + 1
        # Check for various suspicious patterns in the line
        # 1. Antigravity / ChatGPT / Claude / Gemini / LLM / OpenAI / Copilot
        # 2. Prompt [0-9] / prompt [0-9]
        # 3. user request / The user / per user / user wants / user asked / user's / user specified
        # 4. Auto-generated / Autogenerated / Fixed by
        # 5. Internal reasoning / monologue comments like "Wait,", "Note: This will be", "Let's", "I need to", "I will", "We should"
        
        # Check line content
        stripped = line.strip()
        
        # Pattern checks
        ai_patterns = [
            (r'antigravity', 'Antigravity reference'),
            (r'chatgpt|gpt-[34]|openai|claude|copilot|gemini|llm\b', 'AI/LLM reference'),
            (r'\bprompt\s*\d+', 'Prompt engineering iteration reference'),
            (r'auto-generated|autogenerated|generated by antigravity', 'Auto-generation header'),
            (r'fixed by\s+antigravity', 'Fixed by AI credit'),
            (r'per user request|user wants|user request|user asked|the user\b|per user\b', 'Conversational / User dialogue reference'),
            (r'\bwait,\s*kubejs|\bwait,\s*we\b|\bwait,\s*i\b', 'Internal LLM reasoning artifact'),
            (r'will be (?:further )?(?:defined|refined|handled) in prompt', 'Multi-prompt iteration marker'),
            (r'handled in prompt', 'Multi-prompt iteration marker'),
            (r'defined in prompt', 'Multi-prompt iteration marker'),
            (r'narrative connection for prompt', 'Multi-prompt iteration marker'),
        ]
        
        for pat, desc in ai_patterns:
            if re.search(pat, line, re.IGNORECASE):
                findings.append({
                    'file': rel_path,
                    'line': line_num,
                    'content': line.rstrip(),
                    'type': desc,
                    'pattern': pat
                })

print(f"Direct pattern matches: {len(findings)}")
for f in findings:
    print(f"[{f['file']}:{f['line']}] ({f['type']})\n  {f['content']}")
