#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 21 17:29:28 BOT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=1
shaderPack=ReShaded [v.1.4.2] 26.1.zip
