#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Aug 13 17:00:27 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=1
shaderPack=ReShaded [v.1.4.2] 26.1.zip
