import os
import json
import glob

kubejs_data = r"c:\Users\chris\AppData\Roaming\PrismLauncher\instances\PEAK-dev\minecraft\kubejs\data"
out_js = r"c:\Users\chris\AppData\Roaming\PrismLauncher\instances\PEAK-dev\minecraft\kubejs\server_scripts\20_fixed_datapacks.js"

with open(out_js, 'w', encoding='utf-8') as f_out:
    f_out.write("// Auto-generated by Antigravity to fix broken datapack recipes\n")
    f_out.write("ServerEvents.recipes(event => {\n")
    
    count = 0
    for root, dirs, files in os.walk(kubejs_data):
        for f in files:
            if f.endswith('.json'):
                path = os.path.join(root, f)
                rel_path = os.path.relpath(path, kubejs_data).replace('\\', '/')
                parts = rel_path.split('/')
                if len(parts) >= 3:
                    ns = parts[0]
                    # parts[1] is recipe
                    recipe_path = '/'.join(parts[2:]).replace('.json', '')
                    recipe_id = f"{ns}:{recipe_path}"
                    
                    with open(path, 'r', encoding='utf-8') as jf:
                        try:
                            obj = json.load(jf)
                            f_out.write(f"    event.custom({json.dumps(obj)}).id('{recipe_id}');\n")
                            count += 1
                        except:
                            pass
    
    f_out.write("});\n")

print(f"Successfully converted {count} recipes to KubeJS script!")
