// Archivo generado automáticamente para corregir las recetas rotas de Create en 1.21.1
ServerEvents.recipes(event => {
    event.recipes.create.mixing('4x createdieselgenerators:asphalt_block', ['minecraft:gravel', 'minecraft:gravel', 'minecraft:sand', 'minecraft:sand', Fluid.of('createdieselgenerators:crude_oil', 100)]).id('createdieselgenerators:mixing/asphalt_block')
    event.recipes.create.mixing('200x createdieselgenerators:biodiesel', [Fluid.of('createdieselgenerators:plant_oil', 100), Fluid.of('createdieselgenerators:ethanol', 100)]).id('createdieselgenerators:mixing/biodiesel')
    event.recipes.create.mixing(['1000x createdieselgenerators:black_cement', 'minecraft:black_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:black_concrete_powder']).id('createdieselgenerators:mixing/black_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:blue_cement', 'minecraft:blue_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:blue_concrete_powder']).id('createdieselgenerators:mixing/blue_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:brown_cement', 'minecraft:brown_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:brown_concrete_powder']).id('createdieselgenerators:mixing/brown_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:cyan_cement', 'minecraft:cyan_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:cyan_concrete_powder']).id('createdieselgenerators:mixing/cyan_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:gray_cement', 'minecraft:gray_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:gray_concrete_powder']).id('createdieselgenerators:mixing/gray_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:green_cement', 'minecraft:green_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:green_concrete_powder']).id('createdieselgenerators:mixing/green_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:light_blue_cement', 'minecraft:light_blue_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:light_blue_concrete_powder']).id('createdieselgenerators:mixing/light_blue_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:light_gray_cement', 'minecraft:light_gray_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:light_gray_concrete_powder']).id('createdieselgenerators:mixing/light_gray_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:lime_cement', 'minecraft:lime_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:lime_concrete_powder']).id('createdieselgenerators:mixing/lime_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:magenta_cement', 'minecraft:magenta_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:magenta_concrete_powder']).id('createdieselgenerators:mixing/magenta_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:orange_cement', 'minecraft:orange_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:orange_concrete_powder']).id('createdieselgenerators:mixing/orange_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:pink_cement', 'minecraft:pink_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:pink_concrete_powder']).id('createdieselgenerators:mixing/pink_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:purple_cement', 'minecraft:purple_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:purple_concrete_powder']).id('createdieselgenerators:mixing/purple_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:red_cement', 'minecraft:red_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:red_concrete_powder']).id('createdieselgenerators:mixing/red_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:white_cement', 'minecraft:white_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:white_concrete_powder']).id('createdieselgenerators:mixing/white_concrete')
    event.recipes.create.mixing(['1000x createdieselgenerators:yellow_cement', 'minecraft:yellow_concrete_powder'], [Fluid.of('minecraft:water', 100), 'minecraft:yellow_concrete_powder']).id('createdieselgenerators:mixing/yellow_concrete')
    event.recipes.create.compacting('create:andesite_alloy', ['#c:crushed_raw_materials/andesite', '#c:andesite_alloy_nuggets']).heated().id('createmetalwork:create/compacting/andesite_alloy_from_compacting_heated')
    event.recipes.create.compacting('create:andesite_alloy', [Fluid.of('#c:molten_andesite_alloy', 111)]).id('createmetalwork:create/compacting/andesite_alloy_from_compacting_molten')
    event.recipes.create.compacting('create:brass_ingot', [Fluid.of('#c:molten_brass', 111)]).id('createmetalwork:create/compacting/brass_ingot_from_compacting_molten')
    event.recipes.create.compacting('minecraft:copper_ingot', ['#c:crushed_raw_materials/copper']).heated().id('createmetalwork:create/compacting/copper_ingot_from_compacting_heated')
    event.recipes.create.compacting('minecraft:copper_ingot', [Fluid.of('#c:molten_copper', 111)]).id('createmetalwork:create/compacting/copper_ingot_from_compacting_molten')
    event.recipes.create.compacting('minecraft:gold_ingot', ['#c:crushed_raw_materials/gold']).heated().id('createmetalwork:create/compacting/gold_ingot_from_compacting_heated')
    event.recipes.create.compacting('minecraft:gold_ingot', [Fluid.of('#c:molten_gold', 111)]).id('createmetalwork:create/compacting/gold_ingot_from_compacting_molten')
    event.recipes.create.compacting('minecraft:iron_ingot', ['#c:crushed_raw_materials/iron']).heated().id('createmetalwork:create/compacting/iron_ingot_from_compacting_heated')
    event.recipes.create.compacting('minecraft:iron_ingot', [Fluid.of('#c:molten_iron', 111)]).id('createmetalwork:create/compacting/iron_ingot_from_compacting_molten')
    event.recipes.create.compacting('minecraft:netherite_ingot', [Fluid.of('#c:molten_netherite', 111)]).id('createmetalwork:create/compacting/netherite_ingot_from_compacting_molten')
    event.recipes.create.compacting('create:zinc_ingot', ['#c:crushed_raw_materials/zinc']).heated().id('createmetalwork:create/compacting/zinc_ingot_from_compacting_heated')
    event.recipes.create.compacting('create:zinc_ingot', [Fluid.of('#c:molten_zinc', 111)]).id('createmetalwork:create/compacting/zinc_ingot_from_compacting_molten')
    event.recipes.create.compacting('create_ironworks:bronze_ingot', [Fluid.of('#c:molten_bronze', 111)]).id('createmetalwork:create/compat/create_ironworks/compacting/bronze_ingot_from_compacting_molten_bronze_ironworks')
    event.recipes.create.compacting('create_ironworks:steel_ingot', [Fluid.of('#c:molten_steel', 111)]).id('createmetalwork:create/compat/create_ironworks/compacting/steel_ingot_from_compacting_molten_steel_ironworks')
    event.recipes.create.compacting('create_ironworks:tin_ingot', ['#c:crushed_raw_materials/tin']).heated().id('createmetalwork:create/compat/create_ironworks/compacting/tin_ingot_from_compacting_heated_ironworks')
    event.recipes.create.compacting('create_ironworks:tin_ingot', [Fluid.of('#c:molten_tin', 111)]).id('createmetalwork:create/compat/create_ironworks/compacting/tin_ingot_from_compacting_molten_tin_ironworks')
    event.recipes.create.mixing('222x createmetalwork:molten_bronze', ['#c:crushed_raw_materials/copper', '#c:crushed_raw_materials/tin']).heated().id('createmetalwork:create/compat/create_ironworks/mixing/molten_bronze_from_mixing_heated')
    event.recipes.create.mixing('111x createmetalwork:molten_steel', [Fluid.of('#c:molten_iron', 111), '#minecraft:coal']).heated().id('createmetalwork:create/compat/create_ironworks/mixing/molten_steel_from_mixing_heated_molten')
    event.recipes.create.mixing('222x createmetalwork:molten_tin', ['#c:crushed_raw_materials/tin']).heated().id('createmetalwork:create/compat/create_ironworks/mixing/molten_tin_from_mixing_heated')
    event.recipes.create.mixing('111x createmetalwork:molten_bronze', ['#c:ingots/bronze']).heated().id('createmetalwork:create/compat/create_ironworks/mixing/ingot_melting/molten_bronze_from_melting')
    event.recipes.create.mixing('111x createmetalwork:molten_steel', ['#c:ingots/steel']).heated().id('createmetalwork:create/compat/create_ironworks/mixing/ingot_melting/molten_steel_from_melting')
    event.recipes.create.mixing('111x createmetalwork:molten_tin', ['#c:ingots/tin']).heated().id('createmetalwork:create/compat/create_ironworks/mixing/ingot_melting/molten_tin_from_melting')
    event.recipes.create.compacting(['2x createmetalwork:crushed_andesite', 'create_simple_ore_doubling:slag'], ['minecraft:andesite', Fluid.of('minecraft:lava', 50)]).id('createmetalwork:create/compat/create_simple_ore_doubling/compacting/crushed_andesite_from_compacting')
    event.recipes.create.compacting(['3x createmetalwork:crushed_andesite', 'create_simple_ore_doubling:slag'], ['minecraft:andesite']).heated().id('createmetalwork:create/compat/create_simple_ore_doubling/compacting/crushed_andesite_from_compacting_heated')
    event.recipes.create.compacting(['2x createmetalwork:crushed_netherite_scrap', 'createmetalwork:crushed_netherite_scrap', 'create_simple_ore_doubling:slag', 'create_simple_ore_doubling:slag'], ['minecraft:netherite_scrap', Fluid.of('minecraft:lava', 50)]).id('createmetalwork:create/compat/create_simple_ore_doubling/compacting/crushed_netherite_scrap_from_compacting')
    event.recipes.create.compacting(['3x createmetalwork:crushed_netherite_scrap', 'createmetalwork:crushed_netherite_scrap', 'create_simple_ore_doubling:slag', 'create_simple_ore_doubling:slag'], ['minecraft:netherite_scrap']).heated().id('createmetalwork:create/compat/create_simple_ore_doubling/compacting/crushed_netherite_scrap_from_compacting_heated')
    event.recipes.create.compacting(['2x create:crushed_raw_tin', 'create_simple_ore_doubling:slag'], ['#c:raw_materials/tin', Fluid.of('minecraft:lava', 50)]).id('createmetalwork:create/compat/create_simple_ore_doubling/compacting/crushed_raw_tin_from_compacting')
    event.recipes.create.compacting(['3x create:crushed_raw_tin', 'create_simple_ore_doubling:slag'], ['#c:raw_materials/tin']).heated().id('createmetalwork:create/compat/create_simple_ore_doubling/compacting/crushed_raw_tin_from_compacting_heated')
    event.recipes.create.crushing(['9x createmetalwork:crushed_andesite', 'createmetalwork:crushed_andesite', 'create:experience_nugget'], ['minecraft:andesite']).id('createmetalwork:create/crushing/crushed_andesite_from_crushing')
    event.recipes.create.crushing(['createmetalwork:crushed_netherite_scrap', 'createmetalwork:crushed_netherite_scrap', 'create:experience_nugget', 'create:experience_nugget'], ['minecraft:netherite_scrap']).id('createmetalwork:create/crushing/crushed_netherite_scrap_from_crushing')
    event.recipes.create.crushing(['2x create:crushed_raw_gold', 'create:crushed_raw_gold', '2x create:experience_nugget', 'minecraft:netherrack'], ['minecraft:nether_gold_ore']).id('createmetalwork:create/crushing/crushed_raw_gold_from_crushing_nether_gold_ore')
    event.recipes.create.mixing('222x createmetalwork:molten_andesite_alloy', ['#c:crushed_raw_materials/andesite', '#c:andesite_alloy_nuggets']).heated().id('createmetalwork:create/mixing/molten_andesite_alloy_from_mixing_heated')
    event.recipes.create.mixing('222x createmetalwork:molten_andesite_alloy', [Fluid.of('#c:molten_andesite', 111), Fluid.of('#c:molten_iron', 12)]).heated().id('createmetalwork:create/mixing/molten_andesite_alloy_from_mixing_heated_molten_iron')
    event.recipes.create.mixing('222x createmetalwork:molten_andesite_alloy', [Fluid.of('#c:molten_andesite', 111), Fluid.of('#c:molten_zinc', 12)]).heated().id('createmetalwork:create/mixing/molten_andesite_alloy_from_mixing_heated_molten_zinc')
    event.recipes.create.mixing('222x createmetalwork:molten_andesite', ['#c:crushed_raw_materials/andesite']).heated().id('createmetalwork:create/mixing/molten_andesite_from_mixing_heated')
    event.recipes.create.mixing('1000x createmetalwork:molten_andesite', ['minecraft:andesite']).heated().id('createmetalwork:create/mixing/molten_andesite_from_mixing_heated_alt')
    event.recipes.create.mixing('444x createmetalwork:molten_brass', ['#c:crushed_raw_materials/copper', '#c:crushed_raw_materials/zinc']).heated().id('createmetalwork:create/mixing/molten_brass_from_mixing_heated')
    event.recipes.create.mixing('444x createmetalwork:molten_brass', [Fluid.of('#c:molten_copper', 111), Fluid.of('#c:molten_zinc', 111)]).heated().id('createmetalwork:create/mixing/molten_brass_from_mixing_heated_molten')
    event.recipes.create.mixing('222x createmetalwork:molten_copper', ['#c:crushed_raw_materials/copper']).heated().id('createmetalwork:create/mixing/molten_copper_from_mixing_heated')
    event.recipes.create.mixing('222x createmetalwork:molten_gold', ['#c:crushed_raw_materials/gold']).heated().id('createmetalwork:create/mixing/molten_gold_from_mixing_heated')
    event.recipes.create.mixing('222x createmetalwork:molten_iron', ['#c:crushed_raw_materials/iron']).heated().id('createmetalwork:create/mixing/molten_iron_from_mixing_heated')
    event.recipes.create.mixing('222x createmetalwork:molten_netherite', ['#c:crushed_raw_materials/gold', '#c:crushed_raw_materials/gold', '#c:crushed_raw_materials/gold', '#c:crushed_raw_materials/gold', '#c:crushed_raw_materials/netherite_scrap', '#c:crushed_raw_materials/netherite_scrap', '#c:crushed_raw_materials/netherite_scrap', '#c:crushed_raw_materials/netherite_scrap']).heated().id('createmetalwork:create/mixing/molten_netherite_from_mixing_heated')
    event.recipes.create.mixing('222x createmetalwork:molten_netherite', [Fluid.of('#c:molten_gold', 444), '#c:crushed_raw_materials/netherite_scrap', '#c:crushed_raw_materials/netherite_scrap', '#c:crushed_raw_materials/netherite_scrap', '#c:crushed_raw_materials/netherite_scrap']).heated().id('createmetalwork:create/mixing/molten_netherite_from_mixing_heated_molten')
    event.recipes.create.mixing('222x createmetalwork:molten_zinc', ['#c:crushed_raw_materials/zinc']).heated().id('createmetalwork:create/mixing/molten_zinc_from_mixing_heated')
    event.recipes.create.mixing('111x createmetalwork:molten_andesite_alloy', ['create:andesite_alloy']).heated().id('createmetalwork:create/mixing/ingot_melting/molten_andesite_alloy_from_melting')
    event.recipes.create.mixing('111x createmetalwork:molten_brass', ['#c:ingots/brass']).heated().id('createmetalwork:create/mixing/ingot_melting/molten_brass_from_melting')
    event.recipes.create.mixing('111x createmetalwork:molten_copper', ['#c:ingots/copper']).heated().id('createmetalwork:create/mixing/ingot_melting/molten_copper_from_melting')
    event.recipes.create.mixing('111x createmetalwork:molten_gold', ['#c:ingots/gold']).heated().id('createmetalwork:create/mixing/ingot_melting/molten_gold_from_melting')
    event.recipes.create.mixing('111x createmetalwork:molten_iron', ['#c:ingots/iron']).heated().id('createmetalwork:create/mixing/ingot_melting/molten_iron_from_melting')
    event.recipes.create.mixing('111x createmetalwork:molten_netherite', ['#c:ingots/netherite']).heated().id('createmetalwork:create/mixing/ingot_melting/molten_netherite_from_melting')
    event.recipes.create.mixing('111x createmetalwork:molten_zinc', ['#c:ingots/zinc']).heated().id('createmetalwork:create/mixing/ingot_melting/molten_zinc_from_melting')
    event.recipes.create.compacting('3.0x ae2:fluix_glass_cable', ['ae2:quartz_fiber', 'ae2:fluix_crystal']).heated().id('create_ae2recipes:compacting/fluix_glass_cable')
    event.recipes.create.compacting('3.0x ae2:quartz_fiber', ['#c:glass_blocks', '#c:glass_blocks', '#c:glass_blocks', 'ae2:certus_quartz_dust', 'ae2:certus_quartz_dust']).heated().id('create_ae2recipes:compacting/quartz_fiber')
    event.recipes.create.cutting('4x ae2:cable_anchor', ['#ae2:metal_ingots']).id('create_ae2recipes:cutting/cable_anchor')
    event.recipes.create.deploying('ae2:fluix_covered_cable', ['ae2:fluix_glass_cable', '#minecraft:wool']).id('create_ae2recipes:deploying/cable/fluix_covered_cable')
    event.recipes.create.deploying('ae2:fluix_smart_cable', ['ae2:fluix_covered_cable', 'ae2:semi_dark_monitor']).id('create_ae2recipes:deploying/cable/fluix_smart_cable')
    event.recipes.create.deploying('ae2:fluix_smart_dense_cable', ['ae2:fluix_covered_dense_cable', 'ae2:semi_dark_monitor']).id('create_ae2recipes:deploying/cable/fluix_smart_dense_cable')
    event.recipes.create.deploying('ae2:capacity_card', ['ae2:basic_card', [{'item': 'ae2:certus_quartz_crystal'}, {'item': 'ae2:charged_certus_quartz_crystal'}]]).id('create_ae2recipes:deploying/card/capacity_card')
    event.recipes.create.deploying('ae2:crafting_card', ['ae2:basic_card', 'minecraft:crafting_table']).id('create_ae2recipes:deploying/card/crafting_card')
    event.recipes.create.deploying('ae2:energy_card', ['ae2:advanced_card', 'ae2:dense_energy_cell']).id('create_ae2recipes:deploying/card/energy_card')
    event.recipes.create.deploying('ae2:equal_distribution_card', ['ae2:advanced_card', 'ae2:calculation_processor']).id('create_ae2recipes:deploying/card/equal_distribution_card')
    event.recipes.create.deploying('ae2:fuzzy_card', ['ae2:advanced_card', '#minecraft:wool']).id('create_ae2recipes:deploying/card/fuzzy_card')
    event.recipes.create.deploying('ae2:inverter_card', ['ae2:advanced_card', 'minecraft:redstone_torch']).id('create_ae2recipes:deploying/card/inverter_card')
    event.recipes.create.deploying('ae2:redstone_card', ['ae2:basic_card', 'minecraft:redstone_torch']).id('create_ae2recipes:deploying/card/redstone_card')
    event.recipes.create.deploying('ae2:speed_card', ['ae2:advanced_card', 'ae2:fluix_crystal']).id('create_ae2recipes:deploying/card/speed_card')
    event.recipes.create.deploying('ae2:void_card', ['ae2:basic_card', 'ae2:calculation_processor']).id('create_ae2recipes:deploying/card/void_card')
    event.recipes.create.deploying('ae2:fluid_storage_cell_16k', ['ae2:fluid_cell_housing', 'ae2:cell_component_16k']).id('create_ae2recipes:deploying/cell/fluid_storage_cell_16k')
    event.recipes.create.deploying('ae2:fluid_storage_cell_1k', ['ae2:fluid_cell_housing', 'ae2:cell_component_1k']).id('create_ae2recipes:deploying/cell/fluid_storage_cell_1k')
    event.recipes.create.deploying('ae2:fluid_storage_cell_256k', ['ae2:fluid_cell_housing', 'ae2:cell_component_256k']).id('create_ae2recipes:deploying/cell/fluid_storage_cell_256k')
    event.recipes.create.deploying('ae2:fluid_storage_cell_4k', ['ae2:fluid_cell_housing', 'ae2:cell_component_4k']).id('create_ae2recipes:deploying/cell/fluid_storage_cell_4k')
    event.recipes.create.deploying('ae2:fluid_storage_cell_64k', ['ae2:fluid_cell_housing', 'ae2:cell_component_64k']).id('create_ae2recipes:deploying/cell/fluid_storage_cell_64k')
    event.recipes.create.deploying('ae2:item_storage_cell_16k', ['ae2:item_cell_housing', 'ae2:cell_component_16k']).id('create_ae2recipes:deploying/cell/item_storage_cell_16k')
    event.recipes.create.deploying('ae2:item_storage_cell_1k', ['ae2:item_cell_housing', 'ae2:cell_component_1k']).id('create_ae2recipes:deploying/cell/item_storage_cell_1k')
    event.recipes.create.deploying('ae2:item_storage_cell_256k', ['ae2:item_cell_housing', 'ae2:cell_component_256k']).id('create_ae2recipes:deploying/cell/item_storage_cell_256k')
    event.recipes.create.deploying('ae2:item_storage_cell_4k', ['ae2:item_cell_housing', 'ae2:cell_component_4k']).id('create_ae2recipes:deploying/cell/item_storage_cell_4k')
    event.recipes.create.deploying('ae2:item_storage_cell_64k', ['ae2:item_cell_housing', 'ae2:cell_component_64k']).id('create_ae2recipes:deploying/cell/item_storage_cell_64k')
    event.recipes.create.deploying('ae2:spatial_storage_cell_128', ['ae2:item_cell_housing', 'ae2:spatial_cell_component_128']).id('create_ae2recipes:deploying/cell/spatial_storage_cell_128')
    event.recipes.create.deploying('ae2:spatial_storage_cell_16', ['ae2:item_cell_housing', 'ae2:spatial_cell_component_16']).id('create_ae2recipes:deploying/cell/spatial_storage_cell_16')
    event.recipes.create.deploying('ae2:spatial_storage_cell_2', ['ae2:item_cell_housing', 'ae2:spatial_cell_component_2']).id('create_ae2recipes:deploying/cell/spatial_storage_cell_2')
    event.recipes.create.deploying('ae2:view_cell', ['ae2:item_cell_housing', [{'item': 'ae2:certus_quartz_crystal'}, {'item': 'ae2:charged_certus_quartz_crystal'}]]).id('create_ae2recipes:deploying/cell/view_cell')
    event.recipes.create.deploying('ae2:16k_crafting_storage', ['ae2:crafting_unit', 'ae2:cell_component_16k']).id('create_ae2recipes:deploying/craft_unit/16k_crafting_storage')
    event.recipes.create.deploying('ae2:1k_crafting_storage', ['ae2:crafting_unit', 'ae2:cell_component_1k']).id('create_ae2recipes:deploying/craft_unit/1k_crafting_storage')
    event.recipes.create.deploying('ae2:256k_crafting_storage', ['ae2:crafting_unit', 'ae2:cell_component_256k']).id('create_ae2recipes:deploying/craft_unit/256k_crafting_storage')
    event.recipes.create.deploying('ae2:4k_crafting_storage', ['ae2:crafting_unit', 'ae2:cell_component_4k']).id('create_ae2recipes:deploying/craft_unit/4k_crafting_storage')
    event.recipes.create.deploying('ae2:64k_crafting_storage', ['ae2:crafting_unit', 'ae2:cell_component_64k']).id('create_ae2recipes:deploying/craft_unit/64k_crafting_storage')
    event.recipes.create.deploying('ae2:crafting_accelerator', ['ae2:crafting_unit', 'ae2:engineering_processor']).id('create_ae2recipes:deploying/craft_unit/crafting_accelerator')
    event.recipes.create.deploying('ae2:crafting_monitor', ['ae2:crafting_unit', 'ae2:storage_monitor']).id('create_ae2recipes:deploying/craft_unit/crafting_monitor')
    event.recipes.create.deploying('ae2:crafting_terminal', [[{'item': 'ae2:terminal'}], 'ae2:crafting_card']).id('create_ae2recipes:deploying/network/crafting_terminal')
    event.recipes.create.deploying('ae2:energy_level_emitter', ['ae2:level_emitter', 'ae2:charged_certus_quartz_crystal']).id('create_ae2recipes:deploying/network/energy_level_emitter')
    event.recipes.create.deploying('ae2:level_emitter', ['ae2:calculation_processor', 'minecraft:redstone_torch']).id('create_ae2recipes:deploying/network/level_emitter')
    event.recipes.create.deploying('ae2:pattern_encoding_terminal', ['ae2:crafting_terminal', 'ae2:engineering_processor']).id('create_ae2recipes:deploying/network/pattern_encoding_terminal')
    event.recipes.create.deploying('ae2:storage_bus', [[{'item': 'ae2:interface'}, {'item': 'ae2:cable_interface'}], 'minecraft:piston']).id('create_ae2recipes:deploying/network/storage_bus')
    event.recipes.create.deploying('ae2:storage_monitor', [[{'item': 'ae2:monitor'}, {'item': 'ae2:dark_monitor'}, {'item': 'ae2:semi_dark_monitor'}], 'ae2:level_emitter']).id('create_ae2recipes:deploying/network/storage_monitor')
    event.recipes.create.deploying('ae2:toggle_bus', ['ae2:fluix_glass_cable', 'create:powered_toggle_latch']).id('create_ae2recipes:deploying/network/toggle_bus')
    event.recipes.create.deploying('ae2:calculation_processor_press', ['minecraft:iron_block', 'ae2:calculation_processor_press']).id('create_ae2recipes:deploying/processor/calculation_processer_press')
    event.recipes.create.deploying('ae2:engineering_processor_press', ['minecraft:iron_block', 'ae2:engineering_processor_press']).id('create_ae2recipes:deploying/processor/engineering_processor_press')
    event.recipes.create.deploying('ae2:logic_processor_press', ['minecraft:iron_block', 'ae2:logic_processor_press']).id('create_ae2recipes:deploying/processor/logic_processor_press')
    event.recipes.create.deploying('ae2:printed_calculation_processor', ['ae2:certus_quartz_crystal', 'ae2:calculation_processor_press']).id('create_ae2recipes:deploying/processor/printed_calculation_processor')
    event.recipes.create.deploying('ae2:printed_engineering_processor', ['minecraft:diamond', 'ae2:engineering_processor_press']).id('create_ae2recipes:deploying/processor/printed_engineering_processor')
    event.recipes.create.deploying('ae2:printed_logic_processor', ['minecraft:gold_ingot', 'ae2:logic_processor_press']).id('create_ae2recipes:deploying/processor/printed_logic_processor')
    event.recipes.create.deploying('ae2:printed_silicon', ['#c:silicon', 'ae2:silicon_press']).id('create_ae2recipes:deploying/processor/printed_silicon')
    event.recipes.create.deploying('ae2:silicon_press', ['minecraft:iron_block', 'ae2:silicon_press']).id('create_ae2recipes:deploying/processor/silicon_press')
    event.recipes.create.haunting('ae2:sky_stone_block', ['minecraft:iron_block']).id('create_ae2recipes:haunting/sky_stone_block')
    event.recipes.create.mechanical_crafting([], []).id('create_ae2recipes:mechanical_crafting/conversion_monitor')
    event.recipes.create.mechanical_crafting([], []).id('create_ae2recipes:mechanical_crafting/pattern_access_terminal')
    event.recipes.create.mechanical_crafting([], []).id('create_ae2recipes:mechanical_crafting/terminal')
    event.recipes.create.mixing('minecraft:basalt', ['minecraft:calcite', 'minecraft:iron_ingot', Fluid.of('minecraft:lava', 250)]).id('create_ae2recipes:mixing/basalt')
    event.recipes.create.mixing('2x ae2:certus_quartz_crystal', ['ae2:certus_quartz_dust', 'ae2:charged_certus_quartz_crystal', Fluid.of('minecraft:water', 250)]).id('create_ae2recipes:mixing/certus_quartz_crystal')
    event.recipes.create.mixing('ae2:chipped_budding_quartz', ['ae2:damaged_budding_quartz', 'ae2:charged_certus_quartz_crystal', Fluid.of('minecraft:water', 500)]).id('create_ae2recipes:mixing/chipped_budding_quartz')
    event.recipes.create.mixing('ae2:damaged_budding_quartz', ['ae2:quartz_block', 'ae2:charged_certus_quartz_crystal', Fluid.of('minecraft:water', 500)]).id('create_ae2recipes:mixing/damaged_budding_quartz')
    event.recipes.create.mixing('ae2:flawed_budding_quartz', ['ae2:chipped_budding_quartz', 'ae2:charged_certus_quartz_crystal', Fluid.of('minecraft:water', 500)]).id('create_ae2recipes:mixing/flawed_budding_quartz')
    event.recipes.create.mixing('ae2:flawless_budding_quartz', ['ae2:flawed_budding_quartz', 'ae2:fluix_pearl', 'create:rose_quartz', 'create:experience_nugget', 'minecraft:amethyst_block', Fluid.of('create:potion', 1000)]).superheated().id('create_ae2recipes:mixing/flawless_budding_quartz')
    event.recipes.create.mixing('ae2:fluix_crystal', ['ae2:fluix_dust', 'ae2:charged_certus_quartz_crystal', Fluid.of('minecraft:water', 250)]).id('create_ae2recipes:mixing/fluix_crystal')
    event.recipes.create.mixing('ae2:fluix_pearl', ['minecraft:ender_pearl', 'ae2:fluix_dust', 'ae2:fluix_dust', 'ae2:fluix_dust', 'ae2:fluix_dust', Fluid.of('minecraft:water', 250)]).superheated().id('create_ae2recipes:mixing/fluix_pearl')
    event.recipes.create.mixing('2.0x ae2:quartz_glass', ['ae2:certus_quartz_dust', 'ae2:certus_quartz_dust', '#c:glass_blocks', '#c:glass_blocks']).heated().id('create_ae2recipes:mixing/quartz_glass')
    event.recipes.create.mixing('ae2:quartz_vibrant_glass', ['ae2:quartz_glass', 'minecraft:glowstone_dust']).heated().id('create_ae2recipes:mixing/quartz_vibrant_glass')
    event.recipes.create.sequenced_assembly('ae2:advanced_card', []).id('create_ae2recipes:sequenced_assembly/advanced_card')
    event.recipes.create.sequenced_assembly('ae2:basic_card', []).id('create_ae2recipes:sequenced_assembly/basic_card')
    event.recipes.create.sequenced_assembly('ae2:blank_pattern', []).id('create_ae2recipes:sequenced_assembly/blank_pattern')
    event.recipes.create.sequenced_assembly('ae2:calculation_processor', []).id('create_ae2recipes:sequenced_assembly/calculation_processor')
    event.recipes.create.sequenced_assembly('ae2:cell_component_16k', []).id('create_ae2recipes:sequenced_assembly/cell_component_16k')
    event.recipes.create.sequenced_assembly('ae2:cell_component_1k', []).id('create_ae2recipes:sequenced_assembly/cell_component_1k')
    event.recipes.create.sequenced_assembly('ae2:cell_component_256k', []).id('create_ae2recipes:sequenced_assembly/cell_component_256k')
    event.recipes.create.sequenced_assembly('ae2:cell_component_4k', []).id('create_ae2recipes:sequenced_assembly/cell_component_4k')
    event.recipes.create.sequenced_assembly('ae2:cell_component_64k', []).id('create_ae2recipes:sequenced_assembly/cell_component_64k')
    event.recipes.create.sequenced_assembly('ae2:engineering_processor', []).id('create_ae2recipes:sequenced_assembly/engineering_processor')
    event.recipes.create.sequenced_assembly('ae2:fluid_cell_housing', []).id('create_ae2recipes:sequenced_assembly/fluid_cell_housing')
    event.recipes.create.sequenced_assembly('ae2:item_cell_housing', []).id('create_ae2recipes:sequenced_assembly/item_cell_housing')
    event.recipes.create.sequenced_assembly('ae2:logic_processor', []).id('create_ae2recipes:sequenced_assembly/logic_processor')
    event.recipes.create.sequenced_assembly('ae2:spatial_cell_component_128', []).id('create_ae2recipes:sequenced_assembly/spatial_cell_component_128')
    event.recipes.create.sequenced_assembly('ae2:spatial_cell_component_16', []).id('create_ae2recipes:sequenced_assembly/spatial_cell_component_16')
    event.recipes.create.sequenced_assembly('ae2:spatial_cell_component_2', []).id('create_ae2recipes:sequenced_assembly/spatial_cell_component_2')
    event.recipes.create.compacting('create_confectionery:bar_of_black_chocolate', [Fluid.of('create_confectionery:black_chocolate', 250)]).id('create_confectionery:bar_of_black_chocolate_recipe')
    event.recipes.create.compacting('create_confectionery:bar_of_caramel', [Fluid.of('create_confectionery:caramel', 250)]).id('create_confectionery:bar_of_caramel_recipe')
    event.recipes.create.compacting('create_confectionery:bar_of_ruby_chocolate', [Fluid.of('create_confectionery:ruby_chocolate', 250)]).id('create_confectionery:bar_of_ruby_chocolate_recipe')
    event.recipes.create.compacting('create_confectionery:bar_of_white_chocolate', [Fluid.of('create_confectionery:white_chocolate', 250)]).id('create_confectionery:bar_of_white_chocolate_recipe')
    event.recipes.create.filling('create_confectionery:black_chocolate_candy_1', ['create:bar_of_chocolate', Fluid.of('create_confectionery:black_chocolate', 250)]).id('create_confectionery:black_chocolate_candy_1_recipe')
    event.recipes.create.filling('create_confectionery:black_chocolate_candy_2', ['create_confectionery:bar_of_white_chocolate', Fluid.of('create_confectionery:black_chocolate', 250)]).id('create_confectionery:black_chocolate_candy_2_recipe')
    event.recipes.create.filling('create_confectionery:black_chocolate_candy_3', ['create_confectionery:bar_of_ruby_chocolate', Fluid.of('create_confectionery:black_chocolate', 250)]).id('create_confectionery:black_chocolate_candy_3_recipe')
    event.recipes.create.filling('create_confectionery:black_chocolate_candy', ['create_confectionery:bar_of_caramel', Fluid.of('create_confectionery:black_chocolate', 250)]).id('create_confectionery:black_chocolate_candy_recipe')
    event.recipes.create.emptying(['minecraft:bucket', '1000x create_confectionery:black_chocolate'], ['create_confectionery:black_chocolate_bucket']).id('create_confectionery:black_chocolate_emptying')
    event.recipes.create.filling('create_confectionery:black_chocolate_glazed_berries', ['minecraft:sweet_berries', Fluid.of('create_confectionery:black_chocolate', 250)]).id('create_confectionery:black_chocolate_glazed_berries_recipe')
    event.recipes.create.filling('create_confectionery:black_chocolate_glazed_marshmallow', ['create_confectionery:marshmallow', Fluid.of('create_confectionery:black_chocolate', 250)]).id('create_confectionery:black_chocolate_glazed_marshmallow_recipe')
    event.recipes.create.mixing('250x create_confectionery:black_chocolate', ['minecraft:sugar', 'create_confectionery:cocoa_butter', 'minecraft:cocoa_beans', 'minecraft:cocoa_beans', Fluid.of('#c:milk', 250)]).heated().id('create_confectionery:black_chocolate_recipe')
    event.recipes.create.mixing('250x create_confectionery:black_chocolate', ['create_confectionery:bar_of_black_chocolate']).heated().id('create_confectionery:black_chocolate_recipe_2')
    event.recipes.create.mixing('1000x create_confectionery:black_chocolate', ['create_confectionery:black_chocolate_bricks']).heated().id('create_confectionery:black_chocolate_recipe_3')
    event.recipes.create.mixing('1000x create_confectionery:black_chocolate', ['create_confectionery:black_chocolate_bricks_stairs']).heated().id('create_confectionery:black_chocolate_recipe_4')
    event.recipes.create.mixing('500x create_confectionery:black_chocolate', ['create_confectionery:black_chocolate_bricks_slab']).heated().id('create_confectionery:black_chocolate_recipe_5')
    event.recipes.create.mixing('4x create_confectionery:candy_cane', ['minecraft:sugar', 'minecraft:sugar', 'minecraft:slime_ball', Fluid.of('create:potion', 250)]).heated().id('create_confectionery:candy_cane_recipe')
    event.recipes.create.emptying(['minecraft:bucket', '1000x create_confectionery:caramel'], ['create_confectionery:caramel_bucket']).id('create_confectionery:caramel_emptying')
    event.recipes.create.filling('create_confectionery:caramel_glazed_berries', ['minecraft:sweet_berries', Fluid.of('create_confectionery:caramel', 250)]).id('create_confectionery:caramel_glazed_berries_recipe')
    event.recipes.create.mixing('250x create_confectionery:caramel', ['minecraft:sugar', 'minecraft:sugar', Fluid.of('minecraft:water', 250)]).heated().id('create_confectionery:caramel_recipe')
    event.recipes.create.mixing('250x create_confectionery:caramel', ['create_confectionery:bar_of_caramel']).heated().id('create_confectionery:caramel_recipe_2')
    event.recipes.create.filling('create_confectionery:chocolate_candy_1', ['create_confectionery:bar_of_white_chocolate', Fluid.of('create:chocolate', 250)]).id('create_confectionery:chocolate_candy_1_recipe')
    event.recipes.create.filling('create_confectionery:chocolate_candy_2', ['create_confectionery:bar_of_black_chocolate', Fluid.of('create:chocolate', 250)]).id('create_confectionery:chocolate_candy_2_recipe')
    event.recipes.create.filling('create_confectionery:chocolate_candy_3', ['create_confectionery:bar_of_ruby_chocolate', Fluid.of('create:chocolate', 250)]).id('create_confectionery:chocolate_candy_3_recipe')
    event.recipes.create.filling('create_confectionery:chocolate_candy', ['create_confectionery:bar_of_caramel', Fluid.of('create:chocolate', 250)]).id('create_confectionery:chocolate_candy_recipe')
    event.recipes.create.filling('create_confectionery:chocolate_glazed_marshmallow', ['create_confectionery:marshmallow', Fluid.of('create:chocolate', 250)]).id('create_confectionery:chocolate_glazed_marshmallow_recipe')
    event.recipes.create.mixing('1000x create:chocolate', ['create_confectionery:chocolate_bricks']).heated().id('create_confectionery:chocolate_recipe_3')
    event.recipes.create.mixing('1000x create:chocolate', ['create_confectionery:chocolate_bricks_stairs']).heated().id('create_confectionery:chocolate_recipe_4')
    event.recipes.create.mixing('500x create:chocolate', ['create_confectionery:chocolate_bricks_slab']).heated().id('create_confectionery:chocolate_recipe_5')
    event.recipes.create.crushing(['create_confectionery:cocoa_powder', 'create_confectionery:cocoa_butter'], ['create_confectionery:crushed_cocoa']).id('create_confectionery:cocoa_powder_and_butter_recipe')
    event.recipes.create.pressing('create_confectionery:crushed_cocoa', ['minecraft:cocoa_beans']).id('create_confectionery:crushed_cocoa_recipe')
    event.recipes.create.pressing('create_confectionery:gingerbread_man', ['create_confectionery:gingerdough']).id('create_confectionery:gingerbread_man_recipe')
    event.recipes.create.mixing('create_confectionery:gingerdough', ['minecraft:sugar', 'create:cinder_flour', 'create:wheat_flour', Fluid.of('#c:honey', 250)]).id('create_confectionery:gingerdough_recipe')
    event.recipes.create.mixing('4x create_confectionery:honey_candy', ['minecraft:sugar', 'minecraft:sugar', 'create:wheat_flour', Fluid.of('#c:honey', 250)]).heated().id('create_confectionery:honey_candy_recipe')
    event.recipes.create.filling('create_confectionery:hot_chocolate_bottle', ['minecraft:glass_bottle', Fluid.of('create_confectionery:hot_chocolate', 250)]).id('create_confectionery:hot_chocolate_bottle_recipe')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x create_confectionery:hot_chocolate'], ['create_confectionery:hot_chocolate_bottle']).id('create_confectionery:hot_chocolate_drain')
    event.recipes.create.mixing('250x create_confectionery:hot_chocolate', ['minecraft:sugar', 'create_confectionery:cocoa_powder', 'create_confectionery:cocoa_powder', Fluid.of('#c:milk', 250)]).heated().id('create_confectionery:hot_chocolate_recipe')
    event.recipes.create.mixing('8x create_confectionery:marshmallow', ['minecraft:sugar', 'minecraft:sugar', 'minecraft:slime_ball', Fluid.of('minecraft:water', 250)]).heated().id('create_confectionery:marshmallow_recipe')
    event.recipes.create.filling('create_confectionery:ruby_chocolate_candy_1', ['create:bar_of_chocolate', Fluid.of('create_confectionery:ruby_chocolate', 250)]).id('create_confectionery:ruby_chocolate_candy_1_recipe')
    event.recipes.create.filling('create_confectionery:ruby_chocolate_candy_2', ['create_confectionery:bar_of_white_chocolate', Fluid.of('create_confectionery:ruby_chocolate', 250)]).id('create_confectionery:ruby_chocolate_candy_2_recipe')
    event.recipes.create.filling('create_confectionery:ruby_chocolate_candy_3', ['create_confectionery:bar_of_black_chocolate', Fluid.of('create_confectionery:ruby_chocolate', 250)]).id('create_confectionery:ruby_chocolate_candy_3_recipe')
    event.recipes.create.filling('create_confectionery:ruby_chocolate_candy', ['create_confectionery:bar_of_caramel', Fluid.of('create_confectionery:ruby_chocolate', 250)]).id('create_confectionery:ruby_chocolate_candy_recipe')
    event.recipes.create.emptying(['minecraft:bucket', '1000x create_confectionery:ruby_chocolate'], ['create_confectionery:ruby_chocolate_bucket']).id('create_confectionery:ruby_chocolate_emptying')
    event.recipes.create.filling('create_confectionery:ruby_chocolate_glazed_berries', ['minecraft:sweet_berries', Fluid.of('create_confectionery:ruby_chocolate', 250)]).id('create_confectionery:ruby_chocolate_glazed_berries_recipe')
    event.recipes.create.filling('create_confectionery:ruby_chocolate_glazed_marshmallow', ['create_confectionery:marshmallow', Fluid.of('create_confectionery:ruby_chocolate', 250)]).id('create_confectionery:ruby_chocolate_glazed_marshmallow_recipe')
    event.recipes.create.mixing('250x create_confectionery:ruby_chocolate', ['minecraft:sugar', 'minecraft:dragon_breath', 'minecraft:cocoa_beans', Fluid.of('#c:milk', 250)]).heated().id('create_confectionery:ruby_chocolate_recipe')
    event.recipes.create.mixing('250x create_confectionery:ruby_chocolate', ['create_confectionery:bar_of_ruby_chocolate']).heated().id('create_confectionery:ruby_chocolate_recipe_2')
    event.recipes.create.mixing('1000x create_confectionery:ruby_chocolate', ['create_confectionery:ruby_chocolate_bricks']).heated().id('create_confectionery:ruby_chocolate_recipe_3')
    event.recipes.create.mixing('500x create_confectionery:ruby_chocolate', ['create_confectionery:ruby_chocolate_brick_stairs']).heated().id('create_confectionery:ruby_chocolate_recipe_4')
    event.recipes.create.mixing('500x create_confectionery:ruby_chocolate', ['create_confectionery:ruby_chocolate_brick_slab']).heated().id('create_confectionery:ruby_chocolate_recipe_5')
    event.recipes.create.filling('create_confectionery:white_chocolate_candy_1', ['create:bar_of_chocolate', Fluid.of('create_confectionery:white_chocolate', 250)]).id('create_confectionery:white_chocolate_candy_1_recipe')
    event.recipes.create.filling('create_confectionery:white_chocolate_candy_2', ['create_confectionery:bar_of_black_chocolate', Fluid.of('create_confectionery:white_chocolate', 250)]).id('create_confectionery:white_chocolate_candy_2_recipe')
    event.recipes.create.filling('create_confectionery:white_chocolate_candy_3', ['create_confectionery:bar_of_ruby_chocolate', Fluid.of('create_confectionery:white_chocolate', 250)]).id('create_confectionery:white_chocolate_candy_3_recipe')
    event.recipes.create.filling('create_confectionery:white_chocolate_candy', ['create_confectionery:bar_of_caramel', Fluid.of('create_confectionery:white_chocolate', 250)]).id('create_confectionery:white_chocolate_candy_recipe')
    event.recipes.create.emptying(['minecraft:bucket', '1000x create_confectionery:white_chocolate'], ['create_confectionery:white_chocolate_bucket']).id('create_confectionery:white_chocolate_emptying')
    event.recipes.create.filling('create_confectionery:white_chocolate_glazed_berries', ['minecraft:sweet_berries', Fluid.of('create_confectionery:white_chocolate', 250)]).id('create_confectionery:white_chocolate_glazed_berries_recipe')
    event.recipes.create.filling('create_confectionery:white_chocolate_glazed_marshmallow', ['create_confectionery:marshmallow', Fluid.of('create_confectionery:white_chocolate', 250)]).id('create_confectionery:white_chocolate_glazed_marshmallow_recipe')
    event.recipes.create.mixing('250x create_confectionery:white_chocolate', ['minecraft:sugar', 'create_confectionery:cocoa_butter', Fluid.of('#c:milk', 250)]).heated().id('create_confectionery:white_chocolate_recipe')
    event.recipes.create.mixing('250x create_confectionery:white_chocolate', ['create_confectionery:bar_of_white_chocolate']).heated().id('create_confectionery:white_chocolate_recipe_2')
    event.recipes.create.mixing('1000x create_confectionery:white_chocolate', ['create_confectionery:white_chocolate_bricks']).heated().id('create_confectionery:white_chocolate_recipe_3')
    event.recipes.create.mixing('1000x create_confectionery:white_chocolate', ['create_confectionery:white_chocolate_bricks_stairs']).heated().id('create_confectionery:white_chocolate_recipe_4')
    event.recipes.create.mixing('500x create_confectionery:white_chocolate', ['create_confectionery:white_chocolate_bricks_slab']).heated().id('create_confectionery:white_chocolate_recipe_5')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:andesite_exoskeleton_recipe')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:andesite_jetpack_recipe')
    event.recipes.create.mixing('create_sa:blazing_axe', ['minecraft:golden_axe', 'create:powdered_obsidian']).heated().id('create_sa:blazing_axe_recipe')
    event.recipes.create.mixing('create_sa:blazing_pickaxe', ['minecraft:golden_pickaxe', 'create:powdered_obsidian']).heated().id('create_sa:blazing_pickaxe_recipe')
    event.recipes.create.mixing('create_sa:blazing_shovel', ['minecraft:golden_shovel', 'create:powdered_obsidian']).heated().id('create_sa:blazing_shovel_recipe')
    event.recipes.create.mixing('create_sa:blazing_cleaver', ['minecraft:golden_sword', 'create:powdered_obsidian']).heated().id('create_sa:blazing_sword_recipe')
    event.recipes.create.haunting('minecraft:name_tag', ['minecraft:writable_book']).id('create_sa:book_and_quill_haunting')
    event.recipes.create.filling('minecraft:brain_coral_block', ['minecraft:dead_brain_coral_block', Fluid.of('create:potion', 25)]).id('create_sa:brain_tube_coral_revive')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:brass_drone_recipe')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:brass_exoskeleton_recipe')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:brass_jetpack_recipe')
    event.recipes.create.filling('minecraft:bubble_coral_block', ['minecraft:dead_bubble_coral_block', Fluid.of('create:potion', 25)]).id('create_sa:dead_bubble_coral_revive')
    event.recipes.create.filling('minecraft:fire_coral_block', ['minecraft:dead_fire_coral_block', Fluid.of('create:potion', 25)]).id('create_sa:dead_fire_coral_revive')
    event.recipes.create.filling('minecraft:horn_coral_block', ['minecraft:dead_horn_coral_block', Fluid.of('create:potion', 25)]).id('create_sa:dead_horn_coral_revive')
    event.recipes.create.filling('minecraft:tube_coral_block', ['minecraft:dead_tube_coral_block', Fluid.of('create:potion', 25)]).id('create_sa:dead_tube_coral_revive')
    event.recipes.create.compacting('minecraft:deepslate', ['minecraft:flint', 'minecraft:flint', 'minecraft:flint', Fluid.of('minecraft:lava', 250)]).id('create_sa:deepslate_pressing_recipe')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:flamethrower_recipe')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:grapplin_whisk_recipe')
    event.recipes.create.sequenced_assembly(['create_sa:heat_engine', 'create:zinc_nugget', 'create:andesite_alloy'], []).id('create_sa:heat_engine_recipe')
    event.recipes.create.sequenced_assembly(['create_sa:hydraulic_engine', 'create:copper_sheet', 'create:andesite_alloy'], []).id('create_sa:hydraulic_engine_recipe')
    event.recipes.create.sequenced_assembly('3x minecraft:book', []).id('create_sa:incomplete_book_recipe')
    event.recipes.create.sequenced_assembly('minecraft:cobweb', []).id('create_sa:incomplete_web_recipe')
    event.recipes.create.haunting('minecraft:chainmail_boots', ['minecraft:iron_boots']).id('create_sa:iron_boots_haunting')
    event.recipes.create.haunting('minecraft:chainmail_chestplate', ['minecraft:iron_chestplate']).id('create_sa:iron_chestplate_haunting')
    event.recipes.create.haunting('minecraft:chainmail_helmet', ['minecraft:iron_helmet']).id('create_sa:iron_helmet_haunting')
    event.recipes.create.haunting('minecraft:chainmail_leggings', ['minecraft:iron_leggings']).id('create_sa:iron_leggings_haunting')
    event.recipes.create.mixing('minecraft:magma_cream', ['minecraft:slime_ball']).heated().id('create_sa:magma_cream_recipe')
    event.recipes.create.filling('minecraft:netherrack', ['minecraft:cobblestone', Fluid.of('create:potion', 25)]).id('create_sa:netherrack_recipe')
    event.recipes.create.haunting('minecraft:crying_obsidian', ['minecraft:obsidian']).id('create_sa:obsidian_haunting')
    event.recipes.create.crushing('create:experience_nugget', ['#c:gems/quartz']).id('create_sa:quartz_gem_crushing')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:rose_quartz_axe_recipe')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:rose_quartz_pickaxe_recipe')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:rose_quartz_shovel_recipe')
    event.recipes.create.mechanical_crafting([], []).id('create_sa:rose_quartz_sword_recipe')
    event.recipes.create.filling('minecraft:wet_sponge', ['minecraft:sponge', Fluid.of('minecraft:water', 1000)]).id('create_sa:sponge_filling')
    event.recipes.create.compacting(['minecraft:sponge', '500x minecraft:water'], ['minecraft:wet_sponge']).id('create_sa:sponge_pressing')
    event.recipes.create.sequenced_assembly(['create_sa:steam_engine', 'create:brass_sheet', 'create:andesite_alloy'], []).id('create_sa:steam_engine_recipe')
    event.recipes.create.compacting('2x create:asurine', ['create:zinc_nugget', 'create:zinc_nugget', 'create:zinc_nugget', 'create:zinc_nugget', 'minecraft:gravel', 'minecraft:gravel', Fluid.of('minecraft:water', 100)]).id('create_ultimate_factory:compacting_asurine')
    event.recipes.create.compacting('minecraft:blaze_rod', ['minecraft:blaze_powder', 'minecraft:blaze_powder', 'minecraft:blaze_powder', 'minecraft:blaze_powder', 'minecraft:blaze_powder', 'minecraft:blaze_powder']).id('create_ultimate_factory:compacting_blazepowder')
    event.recipes.create.compacting('minecraft:calcite', ['minecraft:gravel', 'minecraft:bone_meal', 'minecraft:bone_meal', 'minecraft:bone_meal']).id('create_ultimate_factory:compacting_calcite')
    event.recipes.create.compacting('minecraft:diamond', ['minecraft:coal_block', 'minecraft:coal_block', 'minecraft:coal_block', 'minecraft:coal_block', 'minecraft:coal_block', 'minecraft:coal_block', 'minecraft:coal_block', 'minecraft:coal_block', 'minecraft:coal_block', Fluid.of('minecraft:lava', 100)]).heated().id('create_ultimate_factory:compacting_coalblock')
    event.recipes.create.compacting('2x create:crimsite', ['minecraft:iron_nugget', 'minecraft:iron_nugget', 'minecraft:iron_nugget', 'minecraft:iron_nugget', 'minecraft:iron_nugget', 'minecraft:gravel', 'minecraft:gravel', Fluid.of('minecraft:lava', 100)]).id('create_ultimate_factory:compacting_crimsite')
    event.recipes.create.compacting('minecraft:deepslate', ['minecraft:stone', Fluid.of('minecraft:lava', 50)]).id('create_ultimate_factory:compacting_deepslate')
    event.recipes.create.compacting('2x create:ochrum', ['minecraft:gold_nugget', 'minecraft:gold_nugget', 'minecraft:gravel', 'minecraft:gravel', Fluid.of('minecraft:lava', 100)]).id('create_ultimate_factory:compacting_ochrum')
    event.recipes.create.compacting('minecraft:tuff', ['minecraft:cobblestone', 'minecraft:cobblestone', 'minecraft:cobblestone', 'minecraft:cobblestone', 'minecraft:cobblestone', 'minecraft:cobblestone', 'minecraft:cobblestone', 'minecraft:cobblestone', 'minecraft:cobblestone', Fluid.of('minecraft:lava', 50)]).id('create_ultimate_factory:compacting_tuff')
    event.recipes.create.compacting('2x create:veridium', ['create:copper_nugget', 'create:copper_nugget', 'create:copper_nugget', 'create:copper_nugget', 'create:copper_nugget', 'create:copper_nugget', 'create:copper_nugget', 'minecraft:gravel', 'minecraft:gravel', Fluid.of('minecraft:lava', 100)]).id('create_ultimate_factory:compacting_veridium')
    event.recipes.create.crushing(['minecraft:wither_skeleton_skull', 'minecraft:blackstone'], ['minecraft:blackstone']).id('create_ultimate_factory:crushing_blackstone')
    event.recipes.create.crushing(['2x minecraft:brown_mushroom', 'minecraft:brown_mushroom', 'minecraft:red_mushroom'], ['minecraft:brown_mushroom_block']).id('create_ultimate_factory:crushing_brownmushroom')
    event.recipes.create.crushing('minecraft:heart_of_the_sea', ['#create_ultimate_factory:corals']).id('create_ultimate_factory:crushing_coral')
    event.recipes.create.crushing(['create:powdered_obsidian', 'create:powdered_obsidian', 'minecraft:amethyst_shard'], ['minecraft:crying_obsidian']).id('create_ultimate_factory:crushing_cryingobsidian')
    event.recipes.create.crushing(['3x minecraft:bone_meal', '3x minecraft:bone_meal'], ['#create_ultimate_factory:dead_corals']).id('create_ultimate_factory:crushing_deadcorals')
    event.recipes.create.crushing(['minecraft:ender_pearl', 'minecraft:end_stone'], ['minecraft:end_stone']).id('create_ultimate_factory:crushing_endstone')
    event.recipes.create.crushing(['minecraft:quartz', 'minecraft:lapis_lazuli'], ['create:limestone']).id('create_ultimate_factory:crushing_limestone')
    event.recipes.create.crushing(['minecraft:nether_brick', 'minecraft:nether_brick', 'minecraft:netherite_scrap'], ['minecraft:nether_bricks']).id('create_ultimate_factory:crushing_netherite')
    event.recipes.create.crushing(['2x minecraft:red_mushroom', 'minecraft:red_mushroom', 'minecraft:brown_mushroom'], ['minecraft:red_mushroom_block']).id('create_ultimate_factory:crushing_redmushroom')
    event.recipes.create.crushing(['minecraft:red_sand', 'minecraft:nautilus_shell'], ['minecraft:red_sandstone']).id('create_ultimate_factory:crushing_redsandstone')
    event.recipes.create.crushing('minecraft:blaze_powder', ['create:scoria']).id('create_ultimate_factory:crushing_scoria')
    event.recipes.create.crushing('minecraft:glowstone_dust', ['minecraft:soul_sand']).id('create_ultimate_factory:crushing_soulsand')
    event.recipes.create.haunting('minecraft:chorus_fruit', ['minecraft:apple']).id('create_ultimate_factory:haunting_apple')
    event.recipes.create.haunting('minecraft:coal', ['minecraft:charcoal']).id('create_ultimate_factory:haunting_charcoal')
    event.recipes.create.haunting('minecraft:netherrack', ['minecraft:basalt']).id('create_ultimate_factory:haunting_netherrack')
    event.recipes.create.haunting('minecraft:crying_obsidian', ['minecraft:obsidian']).id('create_ultimate_factory:haunting_obsidian')
    event.recipes.create.haunting('minecraft:fermented_spider_eye', ['minecraft:spider_eye']).id('create_ultimate_factory:haunting_spidereye')
    event.recipes.create.haunting('minecraft:wither_rose', ['minecraft:poppy']).id('create_ultimate_factory:haunting_witherrose')
    event.recipes.create.mixing('minecraft:dripstone_block', ['minecraft:calcite', Fluid.of('minecraft:water', 200)]).id('create_ultimate_factory:mixing_dripstone')
    event.recipes.create.mixing('3x minecraft:gunpowder', ['#minecraft:coals', '#minecraft:coals', 'minecraft:blaze_powder']).id('create_ultimate_factory:mixing_gunpowder')
    event.recipes.create.mixing('minecraft:redstone', ['minecraft:netherrack', 'minecraft:flint', Fluid.of('minecraft:lava', 50)]).id('create_ultimate_factory:mixing_redstone')
    event.recipes.create.splashing('minecraft:slime_ball', ['minecraft:magma_cream']).id('create_ultimate_factory:splashing_magma_cream')
    event.recipes.create.splashing('minecraft:blue_ice', ['minecraft:packed_ice']).id('create_ultimate_factory:splashing_packed_ice')
    event.recipes.create.splashing('minecraft:terracotta', ['#minecraft:terracotta']).id('create_ultimate_factory:splashing_terracotta')
    event.recipes.create.crushing(['aeronautics:end_stone_powder', 'aeronautics:end_stone_powder', 'minecraft:ender_pearl'], ['minecraft:end_stone']).id('create_ultimate_factory:compat/aeronautics_crushing_endstone')
    event.recipes.create.mixing('minecraft:end_stone', ['#c:cobblestones', 'aeronautics:end_stone_powder', Fluid.of('minecraft:water', 25)]).id('create_ultimate_factory:compat/aeronautics_mixing_endstonepowder')
    event.recipes.create.crushing(['tfmg:limesand', 'minecraft:quartz', 'minecraft:lapis_lazuli'], ['create:limestone']).id('create_ultimate_factory:compat/tfmg_crushing_limestone')
    event.recipes.create.crushing(['wstweaks:fragment', 'minecraft:blackstone'], ['minecraft:blackstone']).id('create_ultimate_factory:compat/wst_crushing_blackstone')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:blood'], ['irons_spellbooks:blood_vial']).id('irons_spellbooks:create_compat/create_empty_blood_vial')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:common_ink'], ['irons_spellbooks:common_ink']).id('irons_spellbooks:create_compat/create_empty_common_ink')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:epic_ink'], ['irons_spellbooks:epic_ink']).id('irons_spellbooks:create_compat/create_empty_epic_ink')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:evasion_elixir'], ['irons_spellbooks:evasion_elixir']).id('irons_spellbooks:create_compat/create_empty_evasion_elixir')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:greater_evasion_elixir'], ['irons_spellbooks:greater_evasion_elixir']).id('irons_spellbooks:create_compat/create_empty_greater_evasion_elixir')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:greater_healing_elixir'], ['irons_spellbooks:greater_healing_potion']).id('irons_spellbooks:create_compat/create_empty_greater_healing_potion')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:greater_invisibility_elixir'], ['irons_spellbooks:greater_invisibility_elixir']).id('irons_spellbooks:create_compat/create_empty_greater_invisibility_elixir')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:greater_oakskin_elixir'], ['irons_spellbooks:greater_oakskin_elixir']).id('irons_spellbooks:create_compat/create_empty_greater_oakskin_elixir')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:ice_venom'], ['irons_spellbooks:ice_venom_vial']).id('irons_spellbooks:create_compat/create_empty_ice_venom_vial')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:invisibility_elixir'], ['irons_spellbooks:invisibility_elixir']).id('irons_spellbooks:create_compat/create_empty_invisibility_elixir')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:legendary_ink'], ['irons_spellbooks:legendary_ink']).id('irons_spellbooks:create_compat/create_empty_legendary_ink')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:oakskin_elixir'], ['irons_spellbooks:oakskin_elixir']).id('irons_spellbooks:create_compat/create_empty_oakskin_elixir')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:rare_ink'], ['irons_spellbooks:rare_ink']).id('irons_spellbooks:create_compat/create_empty_rare_ink')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:timeless_slurry'], ['irons_spellbooks:timeless_slurry']).id('irons_spellbooks:create_compat/create_empty_timeless_slurry')
    event.recipes.create.emptying(['minecraft:glass_bottle', '250x irons_spellbooks:uncommon_ink'], ['irons_spellbooks:uncommon_ink']).id('irons_spellbooks:create_compat/create_empty_uncommon_ink')
    event.recipes.create.filling('irons_spellbooks:blood_vial', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:blood', 250)]).id('irons_spellbooks:create_compat/create_fill_blood_vial')
    event.recipes.create.filling('irons_spellbooks:common_ink', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:common_ink', 250)]).id('irons_spellbooks:create_compat/create_fill_common_ink')
    event.recipes.create.filling('irons_spellbooks:epic_ink', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:epic_ink', 250)]).id('irons_spellbooks:create_compat/create_fill_epic_ink')
    event.recipes.create.filling('irons_spellbooks:evasion_elixir', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:evasion_elixir', 250)]).id('irons_spellbooks:create_compat/create_fill_evasion_elixir')
    event.recipes.create.filling('irons_spellbooks:greater_evasion_elixir', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:greater_evasion_elixir', 250)]).id('irons_spellbooks:create_compat/create_fill_greater_evasion_elixir')
    event.recipes.create.filling('irons_spellbooks:greater_healing_potion', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:greater_healing_elixir', 250)]).id('irons_spellbooks:create_compat/create_fill_greater_healing_potion')
    event.recipes.create.filling('irons_spellbooks:greater_invisibility_elixir', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:greater_invisibility_elixir', 250)]).id('irons_spellbooks:create_compat/create_fill_greater_invisibility_elixir')
    event.recipes.create.filling('irons_spellbooks:greater_oakskin_elixir', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:greater_oakskin_elixir', 250)]).id('irons_spellbooks:create_compat/create_fill_greater_oakskin_elixir')
    event.recipes.create.filling('irons_spellbooks:ice_venom_vial', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:ice_venom', 250)]).id('irons_spellbooks:create_compat/create_fill_ice_venom_vial')
    event.recipes.create.filling('irons_spellbooks:invisibility_elixir', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:invisibility_elixir', 250)]).id('irons_spellbooks:create_compat/create_fill_invisibility_elixir')
    event.recipes.create.filling('irons_spellbooks:legendary_ink', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:legendary_ink', 250)]).id('irons_spellbooks:create_compat/create_fill_legendary_ink')
    event.recipes.create.filling('irons_spellbooks:oakskin_elixir', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:oakskin_elixir', 250)]).id('irons_spellbooks:create_compat/create_fill_oakskin_elixir')
    event.recipes.create.filling('irons_spellbooks:rare_ink', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:rare_ink', 250)]).id('irons_spellbooks:create_compat/create_fill_rare_ink')
    event.recipes.create.filling('irons_spellbooks:timeless_slurry', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:timeless_slurry', 250)]).id('irons_spellbooks:create_compat/create_fill_timeless_slurry')
    event.recipes.create.filling('irons_spellbooks:uncommon_ink', ['minecraft:glass_bottle', Fluid.of('irons_spellbooks:uncommon_ink', 250)]).id('irons_spellbooks:create_compat/create_fill_uncommon_ink')
})
