// Auto-generated by Antigravity: Tag unifications
ServerEvents.tags('item', event => {
    // Unify screwdrivers
    event.add('c:tools/screwdriver', 'immersiveengineering:screwdriver');
    event.add('c:tools/screwdriver', 'tfmg:screwdriver');
});
