ServerEvents.recipes(event => {
    // Shaped crafting recipes for AllTheOres manual hammer crushing.
    // Using shaped patterns (Hammer on top of material) prevents Create Mechanical Mixers
    // from consuming hammers, while preserving manual crafting in standard 2x2 and 3x3 grids.

    event.shaped('alltheores:aluminum_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/aluminum' }).id('kubejs:crafting/hammer/aluminum_dust_from_ingot');
    event.shaped('2x alltheores:aluminum_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/aluminum' }).id('kubejs:crafting/hammer/aluminum_dust_from_ore');
    event.shaped('2x alltheores:aluminum_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/aluminum' }).id('kubejs:crafting/hammer/aluminum_dust_from_raw');
    event.shaped('alltheores:brass_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/brass' }).id('kubejs:crafting/hammer/brass_dust_from_ingot');
    event.shaped('alltheores:bronze_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/bronze' }).id('kubejs:crafting/hammer/bronze_dust_from_ingot');
    event.shaped('alltheores:cinnabar_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:gems/cinnabar' }).id('kubejs:crafting/hammer/cinnabar_dust_from_gem');
    event.shaped('2x alltheores:cinnabar', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/cinnabar' }).id('kubejs:crafting/hammer/cinnabar_gem_from_ore');
    event.shaped('alltheores:constantan_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/constantan' }).id('kubejs:crafting/hammer/constantan_dust_from_ingot');
    event.shaped('alltheores:copper_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/copper' }).id('kubejs:crafting/hammer/copper_dust_from_ingot');
    event.shaped('2x alltheores:copper_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/copper' }).id('kubejs:crafting/hammer/copper_dust_from_ore');
    event.shaped('2x alltheores:copper_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/copper' }).id('kubejs:crafting/hammer/copper_dust_from_raw');
    event.shaped('alltheores:diamond_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:gems/diamond' }).id('kubejs:crafting/hammer/diamond_dust_from_gem');
    event.shaped('2x alltheores:diamond_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/diamond' }).id('kubejs:crafting/hammer/diamond_dust_from_ore');
    event.shaped('alltheores:electrum_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/electrum' }).id('kubejs:crafting/hammer/electrum_dust_from_ingot');
    event.shaped('alltheores:enderium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/enderium' }).id('kubejs:crafting/hammer/enderium_dust_from_ingot');
    event.shaped('alltheores:fluorite_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:gems/fluorite' }).id('kubejs:crafting/hammer/fluorite_dust_from_gem');
    event.shaped('2x alltheores:fluorite', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/fluorite' }).id('kubejs:crafting/hammer/fluorite_gem_from_ore');
    event.shaped('alltheores:gold_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/gold' }).id('kubejs:crafting/hammer/gold_dust_from_ingot');
    event.shaped('2x alltheores:gold_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/gold' }).id('kubejs:crafting/hammer/gold_dust_from_ore');
    event.shaped('2x alltheores:gold_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/gold' }).id('kubejs:crafting/hammer/gold_dust_from_raw');
    event.shaped('alltheores:invar_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/invar' }).id('kubejs:crafting/hammer/invar_dust_from_ingot');
    event.shaped('alltheores:iridium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/iridium' }).id('kubejs:crafting/hammer/iridium_dust_from_ingot');
    event.shaped('2x alltheores:iridium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/iridium' }).id('kubejs:crafting/hammer/iridium_dust_from_ore');
    event.shaped('2x alltheores:iridium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/iridium' }).id('kubejs:crafting/hammer/iridium_dust_from_raw');
    event.shaped('alltheores:iron_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/iron' }).id('kubejs:crafting/hammer/iron_dust_from_ingot');
    event.shaped('2x alltheores:iron_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/iron' }).id('kubejs:crafting/hammer/iron_dust_from_ore');
    event.shaped('2x alltheores:iron_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/iron' }).id('kubejs:crafting/hammer/iron_dust_from_raw');
    event.shaped('alltheores:lead_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/lead' }).id('kubejs:crafting/hammer/lead_dust_from_ingot');
    event.shaped('2x alltheores:lead_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/lead' }).id('kubejs:crafting/hammer/lead_dust_from_ore');
    event.shaped('2x alltheores:lead_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/lead' }).id('kubejs:crafting/hammer/lead_dust_from_raw');
    event.shaped('alltheores:lumium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/lumium' }).id('kubejs:crafting/hammer/lumium_dust_from_ingot');
    event.shaped('alltheores:netherite_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/netherite' }).id('kubejs:crafting/hammer/netherite_dust_from_ingot');
    event.shaped('2x minecraft:netherite_scrap', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/netherite_scrap' }).id('kubejs:crafting/hammer/netherite_scrap_from_debris');
    event.shaped('alltheores:nickel_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/nickel' }).id('kubejs:crafting/hammer/nickel_dust_from_ingot');
    event.shaped('2x alltheores:nickel_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/nickel' }).id('kubejs:crafting/hammer/nickel_dust_from_ore');
    event.shaped('2x alltheores:nickel_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/nickel' }).id('kubejs:crafting/hammer/nickel_dust_from_raw');
    event.shaped('alltheores:osmium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/osmium' }).id('kubejs:crafting/hammer/osmium_dust_from_ingot');
    event.shaped('2x alltheores:osmium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/osmium' }).id('kubejs:crafting/hammer/osmium_dust_from_ore');
    event.shaped('2x alltheores:osmium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/osmium' }).id('kubejs:crafting/hammer/osmium_dust_from_raw');
    event.shaped('alltheores:peridot_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:gems/peridot' }).id('kubejs:crafting/hammer/peridot_dust_from_gem');
    event.shaped('2x alltheores:peridot', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/peridot' }).id('kubejs:crafting/hammer/peridot_gem_from_ore');
    event.shaped('alltheores:platinum_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/platinum' }).id('kubejs:crafting/hammer/platinum_dust_from_ingot');
    event.shaped('2x alltheores:platinum_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/platinum' }).id('kubejs:crafting/hammer/platinum_dust_from_ore');
    event.shaped('2x alltheores:platinum_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/platinum' }).id('kubejs:crafting/hammer/platinum_dust_from_raw');
    event.shaped('alltheores:ruby_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:gems/ruby' }).id('kubejs:crafting/hammer/ruby_dust_from_gem');
    event.shaped('2x alltheores:ruby', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/ruby' }).id('kubejs:crafting/hammer/ruby_gem_from_ore');
    event.shaped('2x alltheores:salt', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/salt' }).id('kubejs:crafting/hammer/salt_dust_from_ore');
    event.shaped('alltheores:sapphire_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:gems/sapphire' }).id('kubejs:crafting/hammer/sapphire_dust_from_gem');
    event.shaped('2x alltheores:sapphire', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/sapphire' }).id('kubejs:crafting/hammer/sapphire_gem_from_ore');
    event.shaped('alltheores:signalum_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/signalum' }).id('kubejs:crafting/hammer/signalum_dust_from_ingot');
    event.shaped('alltheores:silver_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/silver' }).id('kubejs:crafting/hammer/silver_dust_from_ingot');
    event.shaped('2x alltheores:silver_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/silver' }).id('kubejs:crafting/hammer/silver_dust_from_ore');
    event.shaped('2x alltheores:silver_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/silver' }).id('kubejs:crafting/hammer/silver_dust_from_raw');
    event.shaped('alltheores:steel_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/steel' }).id('kubejs:crafting/hammer/steel_dust_from_ingot');
    event.shaped('2x alltheores:sulfur', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/sulfur' }).id('kubejs:crafting/hammer/sulfur_dust_from_ore');
    event.shaped('alltheores:tin_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/tin' }).id('kubejs:crafting/hammer/tin_dust_from_ingot');
    event.shaped('2x alltheores:tin_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/tin' }).id('kubejs:crafting/hammer/tin_dust_from_ore');
    event.shaped('2x alltheores:tin_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/tin' }).id('kubejs:crafting/hammer/tin_dust_from_raw');
    event.shaped('alltheores:uranium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/uranium' }).id('kubejs:crafting/hammer/uranium_dust_from_ingot');
    event.shaped('2x alltheores:uranium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/uranium' }).id('kubejs:crafting/hammer/uranium_dust_from_ore');
    event.shaped('2x alltheores:uranium_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/uranium' }).id('kubejs:crafting/hammer/uranium_dust_from_raw');
    event.shaped('alltheores:zinc_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ingots/zinc' }).id('kubejs:crafting/hammer/zinc_dust_from_ingot');
    event.shaped('2x alltheores:zinc_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:ores/zinc' }).id('kubejs:crafting/hammer/zinc_dust_from_ore');
    event.shaped('2x alltheores:zinc_dust', ['H', 'M'], { H: '#alltheores:ore_hammers', M: '#c:raw_materials/zinc' }).id('kubejs:crafting/hammer/zinc_dust_from_raw');
});
